export type ServiceHighlight = {
  title: string;
  paragraphs: string[];
  bullets?: string[];
};
export type ServiceFaq = { question: string; answer: string };
export type ServiceLink = { href: string; title: string; description: string };
export type ServiceContentPageData = {
  path: string;
  title: string;
  description: string;
  keywords: string[];
  h1: string;
  intro: string[];
  breadcrumbs: Array<{ label: string; href?: string }>;
  highlights: ServiceHighlight[];
  costFactors: string[];
  processSteps: string[];
  relatedLinks: ServiceLink[];
  faqs: ServiceFaq[];
  cta: {
    title: string;
    description: string;
    label: string;
    secondaryLabel?: string;
    secondaryHref?: string;
  };
  warning?: { title: string; body: string };
};

const defaultCostFactors = [
  "Omvang van de klus en benodigde arbeidsuren",
  "Materiaalkeuze en kwaliteit van onderdelen",
  "Bereikbaarheid van de werklocatie",
  "Complexiteit van bestaande situatie",
  "Regio, planning en eventuele spoed"
];

const processSteps = [
  "Beschrijf je klus, locatie en timing via /aanvraag.",
  "VakConnect koppelt je aanvraag op basis van dienst en werkgebied.",
  "Een passende aangesloten professional kan contact opnemen voor vervolg."
];

const serviceLinkTitles: Record<string, string> = {
  "badkamer": "Badkamer",
  "badkamer/complete-badkamer": "Complete badkamer",
  "badkamer/inloopdouche": "Inloopdouche",
  "badkamer/renovatie": "Renovatie",
  "badkamer/sanitair": "Sanitair",
  "badkamer/tegelen": "Tegelen",
  "badkamer/ventilatie": "Ventilatie",
  "dakdekker": "Dakdekker",
  "dakdekker/dakgoot": "Dakgoot",
  "dakdekker/dakinspectie": "Dakinspectie",
  "dakdekker/dakkapel": "Dakkapel",
  "dakdekker/daklekkage": "Daklekkage",
  "dakdekker/dakpannen-vervangen": "Dakpannen vervangen",
  "dakdekker/dakrenovatie": "Dakrenovatie",
  "dakdekker/nokvorsten": "Nokvorsten",
  "dakdekker/plat-dak": "Plat dak",
  "dakdekker/schoorsteen": "Schoorsteen",
  "elektricien": "Elektricien",
  "elektricien/groepenkast": "Groepenkast",
  "elektricien/krachtstroom": "Krachtstroom",
  "elektricien/stopcontacten": "Stopcontacten",
  "elektricien/storing": "Storing",
  "elektricien/verlichting": "Verlichting",
  "isolatie": "Isolatie",
  "isolatie/dakisolatie": "Dakisolatie",
  "isolatie/gevelisolatie": "Gevelisolatie",
  "isolatie/kruipruimte-isolatie": "Kruipruimte isolatie",
  "isolatie/spouwmuurisolatie": "Spouwmuurisolatie",
  "isolatie/vloerisolatie": "Vloerisolatie",
  "kozijnen": "Kozijnen",
  "kozijnen/aluminium-kozijnen": "Aluminium kozijnen",
  "kozijnen/houten-kozijnen": "Houten kozijnen",
  "kozijnen/kozijnen-vervangen": "Kozijnen vervangen",
  "kozijnen/kunststof-kozijnen": "Kunststof kozijnen",
  "kozijnen/ramen-en-deuren": "Ramen en deuren",
  "loodgieter": "Loodgieter",
  "loodgieter/afvoer": "Afvoer",
  "loodgieter/leidingwerk": "Leidingwerk",
  "loodgieter/lekkage": "Lekkage",
  "loodgieter/sanitair": "Sanitair",
  "loodgieter/spoed": "Spoed",
  "loodgieter/verstopping": "Verstopping",
  "schilder": "Schilder",
  "schilder/binnenschilderwerk": "Binnenschilderwerk",
  "schilder/buitenschilderwerk": "Buitenschilderwerk",
  "schilder/deuren-schilderen": "Deuren schilderen",
  "schilder/kozijnen-schilderen": "Kozijnen schilderen",
  "schilder/plafond-schilderen": "Plafond schilderen",
  "verbouwing": "Verbouwing",
  "verbouwing/aanbouw": "Aanbouw",
  "verbouwing/keuken-verbouwen": "Keuken verbouwen",
  "verbouwing/uitbouw": "Uitbouw",
  "verbouwing/woning-renoveren": "Woning renoveren",
  "verbouwing/zolder-verbouwen": "Zolder verbouwen",
};

function asPath(key: string) {
  return `/${key}`;
}

function toRelatedLink(key: string): ServiceLink {
  const normalizedKey = key.startsWith("/") ? key.slice(1) : key;
  const path = asPath(normalizedKey);
  const title = serviceLinkTitles[normalizedKey] ?? normalizedKey;
  return {
    href: path,
    title,
    description: `Lees meer over ${title.toLowerCase()} en wanneer deze dienst past bij jouw klus.`,
  };
}

function buildMainPage(key: string, config: {
  name: string;
  title: string;
  description: string;
  intro: string[];
  forWhat: string[];
  work: string[];
  problems: string[];
  materials: string[];
  when: string[];
  related: string[];
  faq: string[][];
  cta: string;
}): ServiceContentPageData {
  return {
    path: asPath(key),
    title: config.title,
    description: config.description,
    keywords: [key, config.name.toLowerCase(), "vakman", "VakConnect"],
    h1: config.title,
    intro: config.intro,
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "Diensten", href: "/diensten" },
      { label: config.name },
    ],
    highlights: [
      {
        title: `Waarvoor je een ${config.name.toLowerCase()} kunt inschakelen`,
        paragraphs: ["Deze aanvragen worden via VakConnect vaak geplaatst wanneer er duidelijke technische of onderhoudsvragen spelen."],
        bullets: config.forWhat,
      },
      {
        title: "Belangrijkste werkzaamheden",
        paragraphs: ["Een aangesloten professional stemt de uitvoering af op jouw woning, prioriteiten en planning."],
        bullets: config.work,
      },
      {
        title: "Veelvoorkomende problemen",
        paragraphs: ["Herken je één of meer signalen, dan is het slim om niet te lang te wachten met een aanvraag."],
        bullets: config.problems,
      },
      {
        title: "Keuzes en materialen",
        paragraphs: config.materials,
      },
      {
        title: "Wanneer een vakman inschakelen",
        paragraphs: ["Hoe eerder je helderheid hebt over oorzaak en aanpak, hoe beter je vervolgschade en verrassingen voorkomt."],
        bullets: config.when,
      },
      {
        title: "Welke informatie in je aanvraag helpt",
        paragraphs: [
          "Omschrijf het probleem concreet, voeg foto’s toe als dat veilig kan en noem je gewenste planning.",
          "Zo kan een passende specialist sneller beoordelen wat nodig is en hoe urgent de klus is.",
        ],
      },
    ],
    costFactors: defaultCostFactors,
    processSteps: [
      "Beschrijf je klus en situatie via /aanvraag.",
      `VakConnect koppelt je aanvraag aan een passende ${config.name.toLowerCase()} in de regio.`,
      "Je ontvangt opvolging van een aangesloten professional die bij de aanvraag past.",
    ],
    relatedLinks: config.related.map(toRelatedLink),
    faqs: config.faq.map((item) => ({ question: item[0], answer: item[1] })),
    cta: {
      title: `Vind een passende ${config.name.toLowerCase()} voor jouw klus`,
      description: "Plaats je aanvraag met duidelijke klusinformatie. VakConnect voert het werk niet zelf uit, maar koppelt je aan een passende aangesloten professional.",
      label: config.cta,
      secondaryLabel: "Bekijk hoe het werkt",
      secondaryHref: "/hoe-werkt-het",
    },
  };
}

function buildSubPage(key: string, config: {
  title: string;
  description: string;
  h1: string;
  intro: string[];
  signals: string[];
  causes: string[];
  actions: string[];
  materials: string[];
  delay: string[];
  related: string[];
  faq: string[][];
  cta: string;
  warning?: boolean;
}): ServiceContentPageData {
  const [cluster, subservice] = key.split("/");
  const clusterLabel = serviceLinkTitles[cluster] ?? cluster;

  return {
    path: asPath(key),
    title: config.title,
    description: config.description,
    keywords: [cluster, subservice, "vakman", "VakConnect"],
    h1: config.h1,
    intro: config.intro,
    breadcrumbs: [
      { label: "Home", href: "/" },
      { label: "Diensten", href: "/diensten" },
      { label: clusterLabel, href: asPath(cluster) },
      { label: serviceLinkTitles[key] ?? subservice },
    ],
    highlights: [
      {
        title: "Wat deze dienst inhoudt",
        paragraphs: [
          `Op deze pagina lees je wanneer ${serviceLinkTitles[key].toLowerCase()} relevant is en welke informatie helpt voor een sterke aanvraag via VakConnect.`,
        ],
      },
      {
        title: "Signalen en veelvoorkomende problemen",
        paragraphs: ["Duidelijke signalen maken het makkelijker om snel de juiste specialist te koppelen."],
        bullets: config.signals,
      },
      {
        title: "Mogelijke oorzaken",
        paragraphs: ["De exacte oorzaak verschilt per woning en situatie, maar deze oorzaken komen regelmatig voor."],
        bullets: config.causes,
      },
      {
        title: "Wat een vakman doorgaans doet",
        paragraphs: ["Een aangesloten professional beoordeelt eerst de situatie en bepaalt daarna een passende aanpak."],
        bullets: config.actions,
      },
      {
        title: "Materialen en keuzes",
        paragraphs: config.materials,
      },
      {
        title: "Risico’s van uitstel",
        paragraphs: ["Niet elke klus is direct spoed, maar te lang wachten vergroot vaak de impact."],
        bullets: config.delay,
      },
    ],
    costFactors: defaultCostFactors,
    processSteps,
    relatedLinks: config.related.map(toRelatedLink),
    faqs: config.faq.map((item) => ({ question: item[0], answer: item[1] })),
    cta: {
      title: "Beschrijf je klus en vind een passende specialist",
      description: "Met een complete aanvraag op /aanvraag kan VakConnect je koppelen aan een professional die past bij jouw dienst en regio.",
      label: config.cta,
      secondaryLabel: `Terug naar ${clusterLabel.toLowerCase()}` ,
      secondaryHref: asPath(cluster),
    },
    warning: config.warning
      ? {
          title: "Veiligheid eerst bij elektra",
          body: "Werkzaamheden aan vaste elektrische installaties zijn risicovol. Gebruik deze pagina als keuzehulp en laat de uitvoering over aan een vakman.",
        }
      : undefined,
  };
}

export const serviceMainPages: Record<string, ServiceContentPageData> = {
  "dakdekker": buildMainPage("dakdekker", {"name": "Dakdekker", "title": "Dakdekker nodig? Vind een passende vakman via VakConnect", "description": "Bekijk wanneer je een dakdekker inschakelt, welke dakwerken vaak voorkomen en hoe je via VakConnect een gerichte aanvraag doet.", "intro": ["Een dakprobleem wil je snel en zorgvuldig laten beoordelen. Via VakConnect plaats je één duidelijke aanvraag, waarna een passende vakman in jouw regio kan reageren.", "Deze pagina helpt je met de belangrijkste keuzes, signalen en kostenfactoren rond dakwerk, zodat je aanvraag direct bruikbaar is."], "forWhat": ["Lekkages aan pannendaken of platte daken", "Vervangen of herstellen van dakbedekking", "Onderhoud aan nokvorsten, goten en schoorsteen", "Inspectie bij aankoop, stormschade of terugkerende vochtproblemen"], "work": ["Lokale reparaties aan dakdelen en aansluitingen", "Renovatie van verouderde dakvlakken", "Vervangen van dakpannen of bitumenlagen", "Herstellen van loodaansluitingen en waterafvoer"], "problems": ["Vochtplekken op zolder of plafond", "Losliggende pannen na harde wind", "Terugkerende lekkage rond schoorsteen of dakkapel", "Overlopende goten en slechte afwatering"], "materials": ["Pannendak, bitumen of EPDM vragen elk een andere aanpak", "De levensduur van materiaal bepaalt vaak of herstel of renovatie slimmer is", "Bereikbaarheid en valbeveiliging hebben invloed op uitvoering en planning"], "when": ["Schakel vroeg in bij de eerste lekkagesporen", "Plan inspectie na storm of extreme regenval", "Wacht niet tot binnenafwerking zichtbaar beschadigt"], "related": ["/dakdekker/daklekkage", "/dakdekker/dakrenovatie", "/dakdekker/dakpannen-vervangen", "/dakdekker/plat-dak", "/dakdekker/schoorsteen", "/dakdekker/nokvorsten"], "faq": [["Is een dakinspectie ook zinvol zonder lekkage?", "Ja, vooral bij oudere daken of na zwaar weer kan vroeg inzicht grotere schade voorkomen."], ["Kan ik spoed aangeven?", "Ja, beschrijf in je aanvraag dat het om spoed gaat en voeg duidelijke foto’s toe als dat veilig kan."], ["Doet VakConnect zelf dakwerk?", "Nee, VakConnect is het platform dat je koppelt aan een passende aangesloten professional."]], "cta": "Vraag een passende dakdekker aan"}),
  "schilder": buildMainPage("schilder", {"name": "Schilder", "title": "Schilder vinden voor binnen- of buitenwerk via VakConnect", "description": "Vind een passende schilder voor onderhoud, opfriswerk of bescherming van hout en gevelonderdelen via VakConnect.", "intro": ["Goed schilderwerk gaat over uitstraling én bescherming. Via VakConnect kun je je klus helder omschrijven, van één ruimte tot volledig buitenschilderwerk.", "Met duidelijke informatie over ondergrond, staat van het oppervlak en planning vergroot je de kans op een passende match."], "forWhat": ["Binnenschilderwerk van muren, plafonds en houtwerk", "Buitenschilderwerk voor kozijnen, deuren en geveldelen", "Herstel van bladderende verf of verkleuring", "Onderhoudsschilderwerk om houtrot en vochtproblemen te beperken"], "work": ["Voorbehandeling zoals reinigen, schuren en plamuren", "Grondlagen en afwerking in passende verfsystemen", "Nauwkeurig afplakken en afwerken van randen", "Controle op vochtbelasting en staat van hout"], "problems": ["Bladderende of krijtende verf", "Barstjes en verkleuring door zon of vocht", "Slecht hechtende oude verflagen", "Slijtage op trap, deuren of kozijnen"], "materials": ["Keuze tussen watergedragen en terpentinegedragen systemen", "Binnen vraagt vaak om slijtvaste en goed reinigbare afwerking", "Buiten spelen UV-bestendigheid en vochtbelasting een grotere rol"], "when": ["Plan buitenwerk op tijd voor het natte seizoen", "Pak lokale schade snel aan om vervolgschade te beperken", "Combineer binnenschilderwerk met andere renovatieplanning"], "related": ["/schilder/binnenschilderwerk", "/schilder/buitenschilderwerk", "/schilder/kozijnen-schilderen", "/schilder/deuren-schilderen", "/schilder/plafond-schilderen"], "faq": [["Moet ik zelf verf inkopen?", "Dat hoeft meestal niet. Je kunt in je aanvraag aangeven of je advies over materiaalkeuze wilt."], ["Kan een schilder kleine houtreparaties meenemen?", "Vaak wel, maar geef dit vooraf aan zodat de juiste professional kan reageren."], ["Werkt VakConnect met eigen schilders?", "Nee, VakConnect koppelt je aanvraag aan aangesloten vakmensen."]], "cta": "Vind een passende schilder"}),
  "loodgieter": buildMainPage("loodgieter", {"name": "Loodgieter", "title": "Loodgieter nodig? Plaats je aanvraag via VakConnect", "description": "Voor lekkage, verstopping, leidingwerk of sanitair: vind via VakConnect een passende loodgieter in jouw regio.", "intro": ["Waterproblemen vragen meestal om snelle en nette opvolging. Via VakConnect omschrijf je de situatie en koppel je jouw aanvraag aan een passende loodgieter.", "Met informatie over locatie van het probleem, ernst en bereikbaarheid kan een professional sneller beoordelen wat nodig is."], "forWhat": ["Lekkages bij kraan, leiding, afvoer of cv-aansluiting", "Verstoppingen in keuken, badkamer of toilet", "Aanpassen of vervangen van leidingwerk", "Montage of vervanging van sanitair"], "work": ["Opsporen en herstellen van lekkages", "Reinigen of vrijmaken van afvoertrajecten", "Aanleggen of verplaatsen van waterleidingen", "Aansluiten en afstellen van sanitair"], "problems": ["Vochtplekken of druppelvorming onder leidingen", "Borrelende afvoer en teruglopend water", "Lage waterdruk of wisselende temperatuur", "Terugkerende lekkage na tijdelijke reparatie"], "materials": ["Materiaalkeuze hangt af van bestaande installaties en bereikbaarheid", "Bij vervanging tellen kwaliteit van koppelingen en afsluitpunten mee", "In natte ruimtes is correcte afdichting rond sanitair cruciaal"], "when": ["Schakel direct in bij actieve lekkage", "Wacht niet bij herhaalde verstoppingen", "Laat aanpassingen doen vóór grotere verbouwingen"], "related": ["/loodgieter/lekkage", "/loodgieter/verstopping", "/loodgieter/leidingwerk", "/loodgieter/sanitair", "/loodgieter/spoed"], "faq": [["Is elke lekkage spoed?", "Niet altijd, maar snel handelen voorkomt vaak extra vocht- en gevolgschade."], ["Wat moet ik vermelden bij een verstopping?", "Noem waar de verstopping zit, sinds wanneer en of meerdere afvoeren tegelijk problemen geven."], ["Doet VakConnect zelf installatiewerk?", "Nee, VakConnect verbindt je met een passende specialist."]], "cta": "Plaats je loodgieter-aanvraag"}),
  "elektricien": buildMainPage("elektricien", {"name": "Elektricien", "title": "Elektricien vinden voor veilige elektra via VakConnect", "description": "Voor groepenkast, storingen, stopcontacten, verlichting of krachtstroom: vind via VakConnect een passende elektricien.", "intro": ["Elektra vraagt om vakkennis en veilige uitvoering. Via VakConnect beschrijf je je situatie zodat een passende elektricien gericht kan reageren.", "Met duidelijke informatie over bouwjaar, huidige installatie en aard van de storing voorkom je onnodige vertraging."], "forWhat": ["Uitbreiding of vervanging van groepenkast", "Lokaliseren en oplossen van storingen", "Aanleggen of verplaatsen van stopcontacten", "Aansluiten van verlichting en schakelingen", "Voorbereiding op krachtstroom of zwaardere apparatuur"], "work": ["Inspectie van bestaande installatie", "Meten, beveiligen en vervangen van onderdelen", "Netjes afmonteren en testen van aansluitingen", "Documenteren van uitgevoerde aanpassingen"], "problems": ["Regelmatig uitvallende groepen", "Warme stopcontacten of schakelproblemen", "Onvoldoende capaciteit voor nieuwe apparatuur", "Oude installatie die niet meer past bij huidig gebruik"], "materials": ["Groepenkastopbouw en beveiliging bepalen veel van de aanpak", "Bij uitbreiding tellen kabelroutes en afwerking mee", "Voor buitenverlichting is weerbestendig materiaal nodig"], "when": ["Bij terugkerende storingen direct laten beoordelen", "Voor verbouwing vooraf de belasting laten checken", "Bij twijfel over veiligheid geen risico nemen"], "related": ["/elektricien/groepenkast", "/elektricien/storing", "/elektricien/stopcontacten", "/elektricien/verlichting", "/elektricien/krachtstroom"], "faq": [["Kan ik kleine elektra-klussen zelf doen?", "Voor veiligheid is het verstandig om werkzaamheden aan vaste installatie via een vakman te laten uitvoeren."], ["Welke info helpt bij storingen?", "Noem welke groep uitvalt, wanneer dat gebeurt en welke apparaten dan actief zijn."], ["Werkt VakConnect als installateur?", "Nee, VakConnect koppelt je aan aangesloten professionals."]], "cta": "Vind een passende elektricien"}),
  "kozijnen": buildMainPage("kozijnen", {"name": "Kozijnen", "title": "Kozijnen laten vervangen of onderhouden via VakConnect", "description": "Vergelijk opties voor kunststof, hout en aluminium kozijnen en vind via VakConnect een passende specialist.", "intro": ["Kozijnen hebben invloed op comfort, isolatie en onderhoud. Via VakConnect vraag je gericht hulp aan voor vervanging, herstel of materiaaladvies.", "Door je wensen en de huidige situatie goed te beschrijven, komt je aanvraag sneller bij een passende professional."], "forWhat": ["Vervangen van verouderde kozijnen", "Keuzehulp tussen kunststof, hout en aluminium", "Combinatie met nieuw glas of betere kierdichting", "Aanpak van tocht, condens of slecht sluitwerk"], "work": ["Inmeten en beoordelen van bestaande sparingen", "Demonteren en plaatsen van nieuwe kozijnen", "Afwerken van aansluitingen en beslag", "Controle op luchtdichting en bedienbaarheid"], "problems": ["Tocht en vocht rond ramen of deuren", "Klemmen of slecht sluitende draaiende delen", "Houtrot of slijtage van afwerking", "Onvoldoende isolatiewaarde"], "materials": ["Kunststof vraagt weinig onderhoud en is kleurvast", "Hout biedt veel uitstraling en herstelmogelijkheden", "Aluminium is sterk en geschikt voor slanke profielen"], "when": ["Bij terugkerende tocht of condensproblemen", "Wanneer herstelkosten blijven oplopen", "Als je tegelijk wilt verduurzamen met beter glas"], "related": ["/kozijnen/kunststof-kozijnen", "/kozijnen/houten-kozijnen", "/kozijnen/aluminium-kozijnen", "/kozijnen/kozijnen-vervangen", "/kozijnen/ramen-en-deuren"], "faq": [["Moet alles in één keer vervangen worden?", "Niet per se. Dat hangt af van staat, budget en planning van de woning."], ["Kan ik kozijnwerk combineren met schilderwerk?", "Ja, vooral bij houten kozijnen is combinatie met onderhoudsschilderwerk logisch."], ["Levert VakConnect zelf kozijnen?", "Nee, je gebruikt VakConnect om een passende specialist te vinden."]], "cta": "Start je kozijnen-aanvraag"}),
  "badkamer": buildMainPage("badkamer", {"name": "Badkamer", "title": "Badkamer vernieuwen? Vind een passende specialist via VakConnect", "description": "Van deelrenovatie tot complete badkamer: ontdek keuzes, kostenfactoren en het aanvraagproces via VakConnect.", "intro": ["Een badkamerproject combineert vaak meerdere disciplines. Via VakConnect kun je je plannen gestructureerd delen, zodat een passende specialist kan aanhaken.", "Met informatie over indeling, gewenste materialen en staat van leidingen wordt de eerste beoordeling veel gerichter."], "forWhat": ["Badkamerrenovatie in bestaande woning", "Nieuwe indeling met inloopdouche of extra opbergruimte", "Vervangen van sanitair en tegelwerk", "Combinatie met ventilatie- of leidingaanpassingen"], "work": ["Sloop en voorbereiding van de ruimte", "Aanpassen van water, afvoer en elektra", "Plaatsen van sanitair, tegels en afwerking", "Afkitten, testen en oplevercontrole"], "problems": ["Lekkage rond douche of bad", "Schimmel door slechte ventilatie", "Verouderde indeling of versleten sanitair", "Terugkerende vochtplekken in kit- en voegwerk"], "materials": ["Tegeltype en formaat bepalen deels de montagetijd", "Sanitairkeuze beïnvloedt leidingwerk en opstelling", "Vochtbestendige afwerking verlengt de levensduur"], "when": ["Plan vroeg bij samenloop met andere verbouwingen", "Laat lekkage of vochtproblemen niet doorlopen", "Controleer vooraf of extra ventilatie nodig is"], "related": ["/badkamer/renovatie", "/badkamer/tegelen", "/badkamer/sanitair", "/badkamer/inloopdouche", "/badkamer/complete-badkamer"], "faq": [["Hoe compleet moet mijn plan al zijn?", "Een globale wens is genoeg om te starten. Beschrijf vooral huidige situatie en prioriteiten."], ["Kan ik badkamerwerk combineren met loodgieter en elektricien?", "Ja, die koppeling is vaak nodig; je kunt dit in je aanvraag aangeven."], ["Voert VakConnect badkamerwerk uit?", "Nee, VakConnect is het platform voor matching met vakmensen."]], "cta": "Beschrijf je badkamerklus"}),
  "isolatie": buildMainPage("isolatie", {"name": "Isolatie", "title": "Isolatie specialist vinden via VakConnect", "description": "Voor dak-, vloer-, spouwmuur- en gevelisolatie vind je via VakConnect een passende specialist voor jouw woning.", "intro": ["Goede isolatie verhoogt comfort en kan energieverlies beperken. Via VakConnect kun je jouw situatie beschrijven en gericht in contact komen met een passende specialist.", "Door type woning, bouwjaar en huidige isolatiestatus mee te geven, wordt snel duidelijk welke aanpak kansrijk is."], "forWhat": ["Dakisolatie bij renovatie of warmteverlies", "Spouwmuurisolatie bij onvoldoende gevelprestatie", "Vloerisolatie voor koude vloeren", "Gevelisolatie bij grotere verduurzamingsplannen"], "work": ["Inspecteren van bestaande constructie", "Kiezen van geschikt isolatiemateriaal", "Vakkundig aanbrengen met aandacht voor ventilatie en vocht", "Controle op aansluiting en afwerking"], "problems": ["Koude zones in huis", "Condens of vochtproblemen", "Hoge stookkosten ondanks normaal gebruik", "Tocht langs vloer of gevel"], "materials": ["Materiaalkeuze hangt af van constructie en beschikbare ruimte", "Vochtgedrag en dampopenheid zijn belangrijk bij oudere woningen", "Niet elk isolatietype past bij iedere bouwmethode"], "when": ["Combineer isolatie met geplande renovaties", "Laat bij vochtklachten eerst oorzaak beoordelen", "Pak slecht geïsoleerde bouwdelen stapsgewijs aan"], "related": ["/isolatie/dakisolatie", "/isolatie/spouwmuurisolatie", "/isolatie/vloerisolatie", "/isolatie/gevelisolatie"], "faq": [["Is één isolatiemaatregel altijd genoeg?", "Niet altijd. De beste stap hangt af van waar het meeste verlies optreedt."], ["Kan isolatie zonder ingrijpende verbouwing?", "Soms wel, bijvoorbeeld bij spouwmuur of vloer vanuit kruipruimte."], ["Doet VakConnect zelf isolatiewerk?", "Nee, het platform koppelt je aan een passende professional."]], "cta": "Vind een isolatiespecialist"}),
  "verbouwing": buildMainPage("verbouwing", {"name": "Verbouwing", "title": "Verbouwing plannen? Vind een passende specialist via VakConnect", "description": "Voor aanbouw, uitbouw, zolderverbouwing of renovatie: plaats je verbouwingsaanvraag via VakConnect.", "intro": ["Bij verbouwingen zijn planning, afstemming en vakkennis doorslaggevend. Via VakConnect kun je jouw project gestructureerd omschrijven voor een passende specialist.", "Door scope, gewenste timing en huidige situatie duidelijk te maken, wordt sneller zichtbaar welke professional past."], "forWhat": ["Aanbouw of uitbouw van leefruimte", "Zolder ombouwen tot slaapkamer of werkruimte", "Keuken verbouwen met technische aanpassingen", "Woningrenovatie in fases"], "work": ["Inventarisatie van bestaande constructie", "Ruwe bouwkundige aanpassingen", "Coördinatie van installatiewerk en afbouw", "Oplevering met controle op details"], "problems": ["Onvoldoende ruimte in huidige indeling", "Verouderde delen van de woning", "Onduidelijke fasering tussen disciplines", "Twijfel over haalbaarheid van wensen"], "materials": ["Materiaalkeuze beïnvloedt uitstraling, onderhoud en planning", "Constructieve ingrepen vragen vaak extra voorbereiding", "Afwerkingsniveau heeft veel invloed op budget"], "when": ["Start op tijd met inventarisatie en aanvraag", "Houd rekening met vergunnings- of meldingsplicht", "Plan disciplines samen om vertraging te voorkomen"], "related": ["/verbouwing/aanbouw", "/verbouwing/uitbouw", "/verbouwing/zolder-verbouwen", "/verbouwing/woning-renoveren", "/verbouwing/keuken-verbouwen"], "faq": [["Kan ik ook een deelverbouwing aanvragen?", "Ja, je hoeft niet direct een complete renovatie te starten."], ["Wanneer is extra specialistische hulp nodig?", "Bij constructieve of installatietechnische aanpassingen is specialistische inzet vaak noodzakelijk."], ["Is VakConnect aannemer van het project?", "Nee, VakConnect koppelt je aan passende vakmensen."]], "cta": "Start je verbouwingsaanvraag"}),
};

export const serviceSubPages: Record<string, ServiceContentPageData> = {
  "dakdekker/daklekkage": buildSubPage("dakdekker/daklekkage", {"title": "Daklekkage oplossen via een passende vakman", "description": "Lees signalen, oorzaken en aanpak bij daklekkage en plaats je aanvraag via VakConnect.", "h1": "Daklekkage? Vind via VakConnect een passende vakman", "intro": ["Daklekkage kan snel extra schade veroorzaken aan isolatie, houtwerk en plafonds.", "Met een duidelijke aanvraag via VakConnect kan een passende dakprofessional gericht reageren."], "signals": ["Vochtkringen of druppels aan plafond", "Natte isolatie of muffe geur op zolder", "Lekkage vooral bij wind en slagregen"], "causes": ["Beschadigde dakbedekking of pannen", "Versleten aansluitingen bij schoorsteen of dakkapel", "Verstopte afvoer op plat dak"], "actions": ["Lokaliseren van lekpunt", "Tijdelijk of definitief waterdicht herstellen", "Controleren op vervolgschade"], "materials": ["Bij pannendaken draait het vaak om pannen, nok en onderlaag", "Bij platte daken om naden, opstanden en afvoeren"], "delay": ["Lang wachten vergroot kans op houtrot en schimmel", "Binnenafwerking kan blijvend beschadigen"], "related": ["/dakdekker", "/dakdekker/plat-dak", "/dakdekker/dakinspectie"], "faq": [["Kan ik lekkage zelf dichten?", "Alleen een veilige noodmaatregel, structureel herstel laat je uitvoeren door een vakman."], ["Welke foto’s zijn nuttig?", "Overzicht van binnenzijde, exacte plek en buitenzijde als dat veilig bereikbaar is."], ["Waar meld ik spoed?", "Geef spoed duidelijk aan in je aanvraag naar /aanvraag."]], "cta": "Plaats je aanvraag voor daklekkage"}),
  "dakdekker/dakrenovatie": buildSubPage("dakdekker/dakrenovatie", {"title": "Dakrenovatie plannen met een passende professional", "description": "Wanneer is dakrenovatie logisch en welke keuzes spelen mee? Lees het op deze pagina.", "h1": "Dakrenovatie nodig? Start je aanvraag via VakConnect", "intro": ["Dakrenovatie is vaak relevant bij terugkerende problemen of verouderde opbouw.", "Via VakConnect leg je jouw situatie vast voor een passende specialist."], "signals": ["Terugkerende lekkages ondanks reparaties", "Poreuze dakdelen of versleten afwerking", "Dalend wooncomfort door warmteverlies"], "causes": ["Einde levensduur dakbedekking", "Achterstallig onderhoud", "Onvoldoende aansluiting rond details"], "actions": ["Inspectie van complete dakopbouw", "Advies over herstel of gedeeltelijke vernieuwing", "Gefaseerde of complete renovatie uitvoeren"], "materials": ["Materiaalkeuze hangt af van daktype en gewenste levensduur", "Combinatie met isolatie kan op lange termijn gunstig zijn"], "delay": ["Uitstel maakt lokale schade vaak groter", "Renovatie kan later ingrijpender en duurder worden"], "related": ["/dakdekker", "/isolatie/dakisolatie", "/dakdekker/dakpannen-vervangen"], "faq": [["Is renovatie altijd volledig vervangen?", "Nee, soms volstaat deelrenovatie afhankelijk van de staat."], ["Moet ik isolatie direct meenemen?", "Dat is vaak praktisch als de opbouw toch open gaat."], ["Doet VakConnect de renovatie?", "Nee, VakConnect koppelt je aan een passende professional."]], "cta": "Vraag een dakrenovatie-specialist aan"}),
  "dakdekker/dakpannen-vervangen": buildSubPage("dakdekker/dakpannen-vervangen", {"title": "Dakpannen vervangen via VakConnect", "description": "Voor kapotte of versleten dakpannen: bekijk aanpak, keuzes en kostenfactoren.", "h1": "Dakpannen vervangen? Vind een passende vakman", "intro": ["Versleten of verschoven dakpannen verhogen de kans op lekkage.", "Een gerichte aanvraag helpt om snel de juiste specialist te vinden."], "signals": ["Gebroken pannen op dak of in de tuin", "Natte plekken onder het dakvlak", "Zichtbare scheefstand van rijen"], "causes": ["Stormbelasting", "Veroudering of poreus materiaal", "Beweging in dakconstructie"], "actions": ["Controleren van hele dakvlak", "Vervangen van losse of grotere aantallen pannen", "Herstellen van nok- en randdetails"], "materials": ["Type pan bepaalt beschikbaarheid en uitstraling", "Kleur- en formaatverschillen spelen mee bij deelvervanging"], "delay": ["Kleine schades kunnen uitgroeien tot lekkage", "Onderliggende constructie kan nat worden"], "related": ["/dakdekker", "/dakdekker/nokvorsten", "/dakdekker/dakinspectie"], "faq": [["Kan ik alleen de kapotte pannen laten doen?", "Ja, als de rest nog in goede staat is."], ["Moet de hele rij eruit?", "Dat hangt af van ligging en aansluiting."], ["Wanneer is vervanging van groter deel slimmer?", "Bij brede slijtage of materiaalveroudering."]], "cta": "Start aanvraag voor dakpannen"}),
  "dakdekker/plat-dak": buildSubPage("dakdekker/plat-dak", {"title": "Plat dak laten repareren of vernieuwen", "description": "Lees wat belangrijk is bij onderhoud, reparatie en vernieuwing van een plat dak.", "h1": "Hulp bij een plat dak via VakConnect", "intro": ["Platte daken vragen periodieke controle van naden en afwatering.", "Via VakConnect vind je een specialist die past bij jouw situatie."], "signals": ["Plassen water blijven lang staan", "Scheurtjes of blazen in daklaag", "Lekkage na stevige regen"], "causes": ["Verouderde toplaag", "Onvoldoende afschot", "Verstopte hemelwaterafvoer"], "actions": ["Inspectie van daklaag en details", "Lokale reparatie of deels vervangen", "Verbeteren van afwatering"], "materials": ["Bitumen en EPDM hebben eigen onderhoudsprofiel", "Aansluitdetails bepalen vaak de kwetsbare plekken"], "delay": ["Langdurige vochtbelasting versnelt slijtage", "Lekkage kan verborgen gevolgschade geven"], "related": ["/dakdekker/daklekkage", "/dakdekker/dakgoot", "/dakdekker/dakinspectie"], "faq": [["Hoe vaak inspecteren?", "Minimaal periodiek en na extreem weer."], ["Is reparatie altijd genoeg?", "Niet als de toplaag breed versleten is."], ["Kan een plat dak tegelijk geïsoleerd worden?", "Dat kan, afhankelijk van de opbouw."]], "cta": "Vind een specialist voor plat dak"}),
  "dakdekker/schoorsteen": buildSubPage("dakdekker/schoorsteen", {"title": "Schoorsteenwerk via een dakprofessional", "description": "Voor lood, voegwerk en lekkage rond de schoorsteen: plaats je aanvraag via VakConnect.", "h1": "Schoorsteenwerk regelen via VakConnect", "intro": ["Schoorsteenproblemen ontstaan vaak bij aansluitingen met het dak.", "Met foto’s en duidelijke klachtenomschrijving kan een professional gericht beoordelen."], "signals": ["Vochtplekken rond schoorsteenkanaal", "Los voegwerk of scheuren", "Lood dat los of vervormd is"], "causes": ["Verouderd voegwerk", "Slechte loodaansluiting", "Vorst- en weerschade"], "actions": ["Inspecteren van metselwerk en aansluiting", "Herstellen van loodslabben", "Opnieuw voegen en waterdicht maken"], "materials": ["Kwaliteit van loodvervanger en voegmortel is bepalend", "Bereikbaarheid beïnvloedt de uitvoering"], "delay": ["Lekkage kan via schacht naar binnen trekken", "Los metselwerk kan veiligheidsrisico geven"], "related": ["/dakdekker", "/dakdekker/daklekkage", "/dakdekker/dakkapel"], "faq": [["Valt dit onder dakwerk?", "Meestal wel door de koppeling met dakdetails."], ["Is alleen opnieuw voegen soms voldoende?", "Alleen als de aansluiting verder nog goed is."], ["Wanneer is inspectie verstandig?", "Bij eerste scheuren of vochtsporen."]], "cta": "Vraag schoorsteenhulp aan"}),
  "dakdekker/nokvorsten": buildSubPage("dakdekker/nokvorsten", {"title": "Nokvorsten herstellen of vastzetten via VakConnect", "description": "Losliggende nokvorsten? Lees signalen, oorzaken en aanpak met een passende vakman.", "h1": "Nokvorsten laten herstellen", "intro": ["Nokvorsten vormen de afsluiting van je pannendak en krijgen veel windbelasting.", "Bij scheuren of losliggen is snelle beoordeling verstandig."], "signals": ["Losse of scheef liggende nokdelen", "Scheuren in mortel of bevestiging", "Lekkage langs noklijn"], "causes": ["Verouderde mortel", "Stormbelasting", "Beweging in dakvlak"], "actions": ["Controleren van volledige noklijn", "Opnieuw vastzetten of vernieuwen", "Waterdichte afwerking herstellen"], "materials": ["Mechanische bevestiging en droge noksystemen komen veel voor", "Keuze hangt af van huidige dakopbouw"], "delay": ["Losse delen kunnen verder verschuiven", "Waterindringing rond de nok neemt toe"], "related": ["/dakdekker", "/dakdekker/dakpannen-vervangen", "/dakdekker/dakinspectie"], "faq": [["Is alleen plaatselijk herstel mogelijk?", "Ja, als de rest van de nok nog in goede staat is."], ["Hoe herken ik slijtage?", "Scheuren, loszittende delen en terugkerend vocht zijn duidelijke signalen."], ["Moet ik wachten op lekkage?", "Nee, preventief herstel voorkomt grotere schade."]], "cta": "Start je aanvraag voor nokvorsten"}),
  "dakdekker/dakgoot": buildSubPage("dakdekker/dakgoot", {"title": "Dakgoot reparatie of vervanging via VakConnect", "description": "Problemen met dakgoten? Bekijk signalen, oorzaken en kostenfactoren voor herstel of vervanging.", "h1": "Dakgoot laten repareren of vervangen", "intro": ["Een goed werkende dakgoot voorkomt waterbelasting op gevel en dakrand.", "Via VakConnect kun je snel een passende vakman vinden voor inspectie of herstel."], "signals": ["Overlopende goot bij normale regen", "Lekkage langs gevel", "Doorhangende of roestende delen"], "causes": ["Verstopping door blad en vuil", "Slijtage van verbindingen", "Onvoldoende afschot"], "actions": ["Reinigen en inspecteren", "Herstellen van naden en ophanging", "Gedeeltelijk of volledig vervangen"], "materials": ["Materiaalkeuze beïnvloedt levensduur en onderhoud", "Aansluiting op afvoer is essentieel voor goede werking"], "delay": ["Gevel kan nat blijven met kans op schade", "Water kan richting fundering trekken"], "related": ["/dakdekker", "/dakdekker/plat-dak", "/loodgieter/afvoer"], "faq": [["Is periodiek onderhoud nodig?", "Ja, vooral bij bomen in de buurt."], ["Kan alleen een deel vervangen worden?", "Dat kan wanneer de rest nog in goede staat is."], ["Wat zet ik in mijn aanvraag?", "Lengte, hoogte, bereikbaarheid en zichtbare schade."]], "cta": "Vind een specialist voor dakgoten"}),
  "dakdekker/dakkapel": buildSubPage("dakdekker/dakkapel", {"title": "Dakkapel onderhoud of herstel via VakConnect", "description": "Lekkage of slijtage rond dakkapel? Vind via VakConnect een passende specialist.", "h1": "Dakkapel laten herstellen", "intro": ["Dakkapellen hebben meerdere kritieke aansluitingen waar lekkage kan ontstaan.", "Een goede intake helpt om snel de juiste specialist te koppelen."], "signals": ["Vochtplekken bij zijwangen of plafond", "Tocht rond kozijn", "Scheurtjes in afwerking"], "causes": ["Versleten kit- en loodnaden", "Slechte waterafvoer", "Veroudering van bekleding"], "actions": ["Controleren van aansluitdetails", "Herstellen van afdichting en bekleding", "Verbeteren van afwatering"], "materials": ["Bekleding kan bestaan uit hout, kunststof of plaatmateriaal", "Detailkeuzes bepalen onderhoudsinterval"], "delay": ["Vocht trekt door in isolatie en afwerking", "Kleine naden worden grotere lekpunten"], "related": ["/dakdekker", "/dakdekker/schoorsteen", "/kozijnen/ramen-en-deuren"], "faq": [["Is dakkapelwerk hetzelfde als dakwerk?", "Vaak is gecombineerde kennis nodig van dak en geveldetails."], ["Moet ik binnenfoto’s toevoegen?", "Ja, dat helpt bij eerste diagnose."], ["Kan dit samen met schilderwerk?", "Dat kan, afhankelijk van de staat van de buitenafwerking."]], "cta": "Plaats je dakkapel-aanvraag"}),
  "dakdekker/dakinspectie": buildSubPage("dakdekker/dakinspectie", {"title": "Dakinspectie aanvragen via VakConnect", "description": "Plan een dakinspectie bij slijtage, aankoop of preventief onderhoud.", "h1": "Dakinspectie laten uitvoeren", "intro": ["Een dakinspectie geeft inzicht in de staat van dakdelen en mogelijke risico’s.", "Via VakConnect vraag je een beoordeling aan die past bij jouw type woning."], "signals": ["Twijfel over staat van ouder dak", "Onverklaarbare vochtsporen", "Inspectiebehoefte na storm"], "causes": ["Normale veroudering", "Achterstallig onderhoud", "Onzichtbare schade aan details"], "actions": ["Visuele controle van dakvlak en aansluitingen", "Rapporteren van aandachtspunten", "Advies over onderhoud, herstel of renovatie"], "materials": ["Type dak bepaalt inspectiemethode", "Bereikbaarheid en veiligheid worden vooraf beoordeeld"], "delay": ["Schade blijft langer onzichtbaar", "Onderhoud wordt reactief in plaats van gepland"], "related": ["/dakdekker", "/dakdekker/daklekkage", "/dakdekker/dakrenovatie"], "faq": [["Wanneer inspecteren?", "Bij twijfel, periodiek onderhoud en na extreem weer."], ["Krijg ik direct een prijs?", "Dat hangt af van bevindingen en benodigde werkzaamheden."], ["Is inspectie nuttig zonder klacht?", "Ja, preventieve controle helpt verrassingen voorkomen."]], "cta": "Vraag een dakinspectie aan"}),
  "schilder/binnenschilderwerk": buildSubPage("schilder/binnenschilderwerk", {"title": "Binnenschilderwerk via VakConnect", "description": "Vind een passende schilder voor strak en duurzaam binnenschilderwerk.", "h1": "Binnenschilderwerk laten uitvoeren", "intro": ["Binnenschilderwerk bepaalt de uitstraling en bescherming van je interieur.", "Via VakConnect beschrijf je ruimte, ondergrond en planning in één aanvraag."], "signals": ["Vlekken, strepen of verkleuring op muren", "Beschadigde laklagen op houtwerk", "Slijtage in intensief gebruikte ruimtes"], "causes": ["Vochtbelasting of condens", "Normale gebruikssporen", "Verouderde verfsystemen"], "actions": ["Voorbehandelen van ondergrond", "Aanbrengen van passende grond- en aflagen", "Netjes afwerken van details"], "materials": ["Mat, zijdeglans of hoogglans beïnvloedt uitstraling en onderhoud", "Bij keukens en trappen is slijtvaste verf belangrijk"], "delay": ["Beschadigde lagen hechten steeds slechter", "Ondergrond vraagt later meer herstel"], "related": ["/schilder", "/schilder/plafond-schilderen", "/schilder/deuren-schilderen"], "faq": [["Moet de ruimte leeg zijn?", "Zoveel mogelijk vrijmaken helpt, maar exacte voorbereiding verschilt per klus."], ["Kan één kamer per keer?", "Ja, gefaseerd werken is vaak mogelijk."], ["Is kleuradvies mogelijk?", "Veel professionals kunnen daarin meedenken."]], "cta": "Start je aanvraag voor binnenschilderwerk"}),
  "schilder/buitenschilderwerk": buildSubPage("schilder/buitenschilderwerk", {"title": "Buitenschilderwerk plannen via VakConnect", "description": "Bescherm je woning met passend buitenschilderwerk door een aangesloten vakman.", "h1": "Buitenschilderwerk laten uitvoeren", "intro": ["Buitenschilderwerk beschermt kozijnen en geveldelen tegen weer en slijtage.", "Via VakConnect vind je een passende schilder voor onderhoud of complete aanpak."], "signals": ["Bladderende verf op kozijnen", "Kale plekken op houten delen", "Kleine scheurtjes in afwerking"], "causes": ["UV-belasting", "Vocht en temperatuurwisselingen", "Uitgestelde onderhoudscycli"], "actions": ["Reinigen en schuren", "Herstellen van zwakke plekken", "Opbouwen van nieuw verfsysteem"], "materials": ["Buitenverf vraagt hoge weersbestendigheid", "Goed systeem bestaat uit voorbereiding, grondlaag en afwerking"], "delay": ["Hout blijft langer onbeschermd", "Kans op houtrot neemt toe"], "related": ["/schilder", "/schilder/kozijnen-schilderen", "/kozijnen/houten-kozijnen"], "faq": [["Wanneer plannen?", "Meestal in stabiele weersperioden."], ["Kan alleen voorzijde?", "Ja, deelprojecten zijn mogelijk."], ["Wat geef ik door?", "Aantal gevelzijden, hoogte en huidige staat."]], "cta": "Vraag buitenschilderwerk aan"}),
  "schilder/kozijnen-schilderen": buildSubPage("schilder/kozijnen-schilderen", {"title": "Kozijnen schilderen via VakConnect", "description": "Vind een passende schilder voor onderhoud of opfrissen van kozijnen.", "h1": "Kozijnen laten schilderen", "intro": ["Kozijnen krijgen veel zon en vocht te verwerken.", "Regelmatig schilderen helpt om slijtage en grotere herstelkosten te beperken."], "signals": ["Barstjes of bladders op kozijnen", "Verkleuring of kale plekken", "Beginnende zachte plekken in hout"], "causes": ["Verouderde beschermlaag", "Vocht in naden", "Mechanische slijtage"], "actions": ["Inspecteren van houtconditie", "Schuren, plamuren en gronden", "Aflakken met geschikt systeem"], "materials": ["Kleur en glansgraad beïnvloeden warmteopname en onderhoud", "Bij houten kozijnen is voorbehandeling cruciaal"], "delay": ["Vocht dringt sneller in het hout", "Kleine beschadigingen worden herstelwerk"], "related": ["/schilder", "/kozijnen/houten-kozijnen", "/schilder/buitenschilderwerk"], "faq": [["Kan dit zonder steiger?", "Dat hangt af van hoogte en bereikbaarheid."], ["Moet kitwerk mee?", "Vaak wel bij verouderde naden."], ["Kan ik alleen binnenzijde laten doen?", "Ja, benoem dat in je aanvraag."]], "cta": "Plaats je kozijnen-schilderaanvraag"}),
  "schilder/deuren-schilderen": buildSubPage("schilder/deuren-schilderen", {"title": "Deuren schilderen via VakConnect", "description": "Voor binnen- en buitendeuren: vind een passende schilder via VakConnect.", "h1": "Deuren laten schilderen", "intro": ["Deuren worden intensief gebruikt en vragen slijtvaste afwerking.", "Via VakConnect vraag je eenvoudig een passende schilder aan."], "signals": ["Slijtage rond grepen", "Krassen en stootschade", "Verf die niet meer egaal is"], "causes": ["Dagelijks gebruik", "Vocht of temperatuurwisselingen", "Onvoldoende voorbehandeling"], "actions": ["Demonteren waar nodig", "Herstellen van beschadigingen", "Aflakken in duurzame afwerking"], "materials": ["Laksoort bepaalt krasvastheid en reinigbaarheid", "Binnen en buiten vragen verschillende systemen"], "delay": ["Beschadigingen verdiepen zich", "Ondergrond wordt moeilijker strak af te werken"], "related": ["/schilder", "/schilder/binnenschilderwerk", "/schilder/buitenschilderwerk"], "faq": [["Moet beslag eraf?", "Vaak wel voor een strakke afwerking."], ["Kan op locatie geschilderd worden?", "Ja, dat gebeurt vaak."], ["Hoeveel deuren tegelijk?", "Dat bepaal je zelf in de aanvraag."]], "cta": "Start je deurenschilder-aanvraag"}),
  "schilder/plafond-schilderen": buildSubPage("schilder/plafond-schilderen", {"title": "Plafond schilderen via VakConnect", "description": "Voor egaal plafondwerk zonder strepen: vind een passende schilder.", "h1": "Plafond laten schilderen", "intro": ["Plafonds laten oneffenheden snel zien, zeker bij strijklicht.", "Een passende vakman zorgt voor voorbereiding en gelijkmatige afwerking."], "signals": ["Vlekken of nicotineaanslag", "Haarscheurtjes", "Strepen na eerdere schilderbeurt"], "causes": ["Vocht, rook of vuilopbouw", "Onjuiste verfkeuze", "Onvoldoende primer"], "actions": ["Reinigen en voorstrijken", "Lokale reparatie van scheurtjes", "Gelijkmatig rollen in passende banen"], "materials": ["Dekkracht en open tijd van verf zijn belangrijk", "In vochtige ruimtes is schimmelwerend systeem relevant"], "delay": ["Vlekken slaan door nieuwe lagen heen", "Kleine scheuren worden zichtbaarder"], "related": ["/schilder", "/schilder/binnenschilderwerk", "/badkamer/ventilatie"], "faq": [["Kan alleen het plafond gedaan worden?", "Ja, dat is een veelgevraagde deelklus."], ["Hoe voorkom je strepen?", "Door goede voorbereiding en juiste verwerking per ondergrond."], ["Moet de ruimte leeg?", "Gedeeltelijk vrijmaken is meestal voldoende."]], "cta": "Vraag plafond-schilderwerk aan"}),
  "loodgieter/lekkage": buildSubPage("loodgieter/lekkage", {"title": "Lekkage laten oplossen via VakConnect loodgieter", "description": "Vind een passende loodgieter voor lekkage aan leiding, kraan of afvoer.", "h1": "Lekkage? Vind snel een passende loodgieter", "intro": ["Lekkage kan snel leiden tot vocht- en schimmelproblemen.", "Met een duidelijke intake via VakConnect kan gericht actie worden genomen."], "signals": ["Druppels onder leidingwerk", "Vochtplekken in kast of muur", "Onverklaarbaar waterverlies"], "causes": ["Versleten koppelingen", "Haarscheur in leiding", "Slechte afdichting rond aansluitpunten"], "actions": ["Leklocatie opsporen", "Defecte delen vervangen", "Installatie testen op dichtheid"], "materials": ["Soort leiding en koppeling bepaalt herstelmethode", "Bereikbaarheid achter wanden kan extra werk vragen"], "delay": ["Vocht tast vloeren en wanden aan", "Risico op schimmel neemt toe"], "related": ["/loodgieter", "/loodgieter/spoed", "/badkamer/sanitair"], "faq": [["Is druppellekkage ook urgent?", "Ja, doorlopend vocht veroorzaakt vaak meer schade dan verwacht."], ["Wat zet ik in de aanvraag?", "Plaats van lekkage, sinds wanneer en zichtbare schade."], ["Kan ik hoofdwater afsluiten?", "Bij actieve lekkage is dat vaak verstandig totdat een vakman arriveert."]], "cta": "Plaats je lekkage-aanvraag"}),
  "loodgieter/verstopping": buildSubPage("loodgieter/verstopping", {"title": "Verstopping verhelpen via VakConnect", "description": "Voor hardnekkige verstoppingen in keuken, badkamer of toilet.", "h1": "Verstopping laten verhelpen", "intro": ["Teruglopend water of borrelende afvoer wijst vaak op een blokkade.", "Via VakConnect kun je snel een passende loodgieter vinden."], "signals": ["Water loopt langzaam weg", "Borrelgeluiden uit afvoer", "Terugslag in meerdere afvoeren"], "causes": ["Vet- en zeepophoping", "Vreemde voorwerpen", "Probleem dieper in leidingtraject"], "actions": ["Lokaliseren van blokkade", "Mechanisch of met apparatuur reinigen", "Controleren op doorstroming"], "materials": ["Type afvoer bepaalt gereedschap en aanpak", "Toegangspunten beïnvloeden werktijd"], "delay": ["Volledige blokkade kan ontstaan", "Kans op waterschade en geurhinder groeit"], "related": ["/loodgieter", "/loodgieter/afvoer", "/loodgieter/spoed"], "faq": [["Helpt chemische ontstopper altijd?", "Nee, bij hardnekkige blokkades vaak niet."], ["Wat moet ik doorgeven?", "Waar de verstopping zit en of meerdere punten last hebben."], ["Kan dit terugkomen?", "Ja, bij onderliggende oorzaak in het traject."]], "cta": "Start je verstoppingsaanvraag"}),
  "loodgieter/leidingwerk": buildSubPage("loodgieter/leidingwerk", {"title": "Leidingwerk aanpassen via VakConnect", "description": "Leidingwerk verleggen, vervangen of uitbreiden met een passende loodgieter.", "h1": "Leidingwerk laten aanleggen of aanpassen", "intro": ["Bij keuken- of badkameraanpassingen is leidingwerk vaak onderdeel van de klus.", "Via VakConnect vraag je een specialist aan die past bij je project."], "signals": ["Nieuwe indeling vereist verplaatsing", "Oude leidingen geven storingen", "Druk- of temperatuurproblemen"], "causes": ["Verouderde installatie", "Onhandige bestaande routing", "Uitbreiding van sanitair of apparatuur"], "actions": ["Plan en route bepalen", "Leidingen verleggen of vervangen", "Testen en afpersen"], "materials": ["Materiaalkeuze hangt af van toepassing en bestaande situatie", "Bereikbaarheid van kruipruimte of schacht speelt mee"], "delay": ["Verbouwing loopt vast door ontbrekende voorbereiding", "Noodoplossingen verhogen latere kosten"], "related": ["/loodgieter", "/badkamer/renovatie", "/verbouwing/keuken-verbouwen"], "faq": [["Kan dit in bewoonde woning?", "Ja, vaak gefaseerd met goede planning."], ["Is hak- en breekwerk altijd nodig?", "Niet altijd, dat hangt af van routes."], ["Moet ik exacte tekening hebben?", "Een globale schets helpt al veel."]], "cta": "Beschrijf je leidingwerkklus"}),
  "loodgieter/sanitair": buildSubPage("loodgieter/sanitair", {"title": "Sanitair plaatsen of vervangen via VakConnect", "description": "Van kraan tot complete sanitairopstelling: vind een passende loodgieter.", "h1": "Sanitair laten plaatsen of vervangen", "intro": ["Sanitair moet goed aansluiten op water, afvoer en ventilatie.", "Via VakConnect kun je eenvoudig een specialist koppelen aan je wensen."], "signals": ["Lekkende aansluitingen", "Versleten sanitair", "Wens voor nieuwe opstelling"], "causes": ["Slijtage van onderdelen", "Verouderde aansluitpunten", "Onhandige indeling"], "actions": ["Demonteren en voorbereiden", "Aansluiten en afstellen van nieuw sanitair", "Controle op waterdichtheid"], "materials": ["Kwaliteit van kranen en aansluitsets beïnvloedt duurzaamheid", "Ruimte en maatvoering bepalen productkeuze"], "delay": ["Kans op lekkage en comfortverlies blijft", "Bestaande schade kan groter worden"], "related": ["/loodgieter", "/badkamer/sanitair", "/badkamer/complete-badkamer"], "faq": [["Kan ik eigen sanitair aanleveren?", "Dat kan meestal, vermeld dit vooraf."], ["Wordt kitwerk meegenomen?", "Vaak wel als onderdeel van nette oplevering."], ["Is maatvoering belangrijk?", "Ja, zeker bij kleinere badkamers of toiletten."]], "cta": "Start je sanitair-aanvraag"}),
  "loodgieter/spoed": buildSubPage("loodgieter/spoed", {"title": "Spoed loodgieter aanvragen via VakConnect", "description": "Bij acute lekkage of verstopping: plaats een duidelijke spoedaanvraag via VakConnect.", "h1": "Spoed loodgieter nodig?", "intro": ["Sommige loodgieterproblemen vragen direct handelen.", "Met een complete spoedaanvraag kan sneller de juiste professional reageren."], "signals": ["Actieve waterlekkage", "Volledig verstopte afvoer", "Waterschade die snel toeneemt"], "causes": ["Gesprongen koppeling", "Acute blokkade", "Defect afsluitpunt"], "actions": ["Situatie veilig maken", "Snelle diagnose", "Gerichte nood- en herstelmaatregelen"], "materials": ["Beschikbare onderdelen bepalen deels de directe oplossing", "Definitieve reparatie volgt soms in tweede stap"], "delay": ["Waterschade en herstelkosten lopen snel op", "Risico op uitval van voorzieningen"], "related": ["/loodgieter", "/loodgieter/lekkage", "/dakdekker/daklekkage"], "faq": [["Wat doe ik eerst bij spoed?", "Beperk wateraanvoer waar mogelijk en meld direct de ernst in je aanvraag."], ["Kan spoed ’s avonds?", "Beschikbaarheid verschilt per regio en moment."], ["Welke info versnelt opvolging?", "Locatie, type probleem en foto’s indien veilig."]], "cta": "Plaats een spoedaanvraag"}),
  "elektricien/groepenkast": buildSubPage("elektricien/groepenkast", {"title": "Groepenkast uitbreiden of vervangen via VakConnect", "description": "Vind een passende elektricien voor veilige groepenkast-aanpassingen.", "h1": "Groepenkast laten aanpassen", "intro": ["Een groepenkast moet passen bij het huidige gebruik van je woning.", "Via VakConnect vraag je gericht een elektricien aan voor inspectie of uitbreiding."], "signals": ["Groepen vallen vaak uit", "Nieuwe apparatuur vraagt extra capaciteit", "Verouderde kast zonder moderne beveiliging"], "causes": ["Overbelasting", "Oude componenten", "Uitbreiding zonder herverdeling"], "actions": ["Belasting beoordelen", "Groepen herindelen of uitbreiden", "Beveiliging en werking testen"], "materials": ["Type kast en beveiliging bepalen de scope", "Aansluitruimte en bekabeling tellen mee"], "delay": ["Storingen blijven terugkeren", "Veiligheidsrisico bij overbelasting neemt toe"], "related": ["/elektricien", "/elektricien/storing", "/elektricien/krachtstroom"], "faq": [["Heb ik altijd vervanging nodig?", "Niet altijd, soms volstaat uitbreiding."], ["Kan dit zonder stroomonderbreking?", "Meestal is tijdelijke onderbreking nodig."], ["Doet VakConnect de installatie?", "Nee, je wordt gekoppeld aan een passende vakman."]], "cta": "Vraag een elektricien voor groepenkast", "warning": true}),
  "elektricien/storing": buildSubPage("elektricien/storing", {"title": "Elektra storing oplossen via VakConnect", "description": "Terugkerende stroomstoring? Vind via VakConnect een passende elektricien.", "h1": "Elektra storing laten oplossen", "intro": ["Een storing kan verschillende oorzaken hebben en vraagt een veilige diagnose.", "Via VakConnect kun je snel een passende specialist vinden."], "signals": ["Groep springt direct terug uit", "Deel van woning zonder stroom", "Flikkerende verlichting"], "causes": ["Defect apparaat", "Beschadigde bekabeling", "Probleem in groepenkast"], "actions": ["Storingsbron isoleren", "Meten en controleren", "Defecte componenten vervangen"], "materials": ["Meetapparatuur en passende componenten zijn essentieel", "Toegang tot verdeelpunten beïnvloedt doorlooptijd"], "delay": ["Storing kan verergeren", "Onveilig gebruik van noodoplossingen"], "related": ["/elektricien", "/elektricien/groepenkast", "/elektricien/stopcontacten"], "faq": [["Kan ik zelf meten?", "Werk aan vaste elektra laat je veilig uitvoeren door een professional."], ["Wat noteer ik bij de aanvraag?", "Welke groep, welke ruimte en wanneer de storing optreedt."], ["Is dit altijd spoed?", "Niet altijd, maar veiligheidsklachten wel direct melden."]], "cta": "Start je storing-aanvraag", "warning": true}),
  "elektricien/stopcontacten": buildSubPage("elektricien/stopcontacten", {"title": "Stopcontacten laten plaatsen via VakConnect", "description": "Extra of verplaatste stopcontacten nodig? Vind een passende elektricien.", "h1": "Stopcontacten laten aanleggen of verplaatsen", "intro": ["Goede positionering van stopcontacten verhoogt comfort en veiligheid.", "Via VakConnect kun je je wensen direct laten beoordelen door een passende elektricien."], "signals": ["Te weinig aansluitpunten", "Verlengsnoeren als vaste oplossing", "Loszittende of verouderde stopcontacten"], "causes": ["Veranderde indeling", "Uitbreiding van apparatuur", "Oude installatie"], "actions": ["Locaties bepalen", "Bekabeling veilig aanleggen", "Aansluitingen testen en afwerken"], "materials": ["Inbouw of opbouw verschilt per wandtype", "Belasting bepaalt of aparte groep nodig is"], "delay": ["Onveilige tijdelijke oplossingen blijven in gebruik", "Aanpassingen worden later complexer"], "related": ["/elektricien", "/elektricien/verlichting", "/verbouwing/keuken-verbouwen"], "faq": [["Kan elk punt worden verplaatst?", "Dat hangt af van leidingroute en constructie."], ["Moet alles worden opengebroken?", "Niet altijd, dit verschilt per situatie."], ["Kan ik meerdere ruimtes combineren?", "Ja, geef alle ruimtes in één aanvraag op."]], "cta": "Vraag stopcontacten aan", "warning": true}),
  "elektricien/verlichting": buildSubPage("elektricien/verlichting", {"title": "Verlichting laten installeren via VakConnect", "description": "Voor binnen- en buitenverlichting: vind een passende elektricien.", "h1": "Verlichting laten aanleggen of vervangen", "intro": ["Verlichting draait om sfeer, functionaliteit en veilige aansluiting.", "Via VakConnect kun je je plan duidelijk indienen voor een passende specialist."], "signals": ["Onvoldoende lichtpunten", "Slechte schakeling", "Verouderde armaturen"], "causes": ["Verouderde installatie", "Nieuwe indeling", "Defecte componenten"], "actions": ["Lichtplan vertalen naar aansluitpunten", "Armaturen en schakelaars monteren", "Installatie testen"], "materials": ["Type armatuur bepaalt aansluiting", "In vochtige zones gelden strengere eisen"], "delay": ["Gebruiksgemak blijft beperkt", "Tijdelijke oplossingen blijven nodig"], "related": ["/elektricien", "/elektricien/stopcontacten", "/badkamer/renovatie"], "faq": [["Kan ik dimmers laten toevoegen?", "Ja, mits installatie en armaturen geschikt zijn."], ["Wat geef ik door?", "Aantal lichtpunten en gewenste bediening."], ["Is buitenverlichting anders?", "Ja, materiaal en bescherming moeten geschikt zijn voor buiten."]], "cta": "Start je verlichtingsaanvraag", "warning": true}),
  "elektricien/krachtstroom": buildSubPage("elektricien/krachtstroom", {"title": "Krachtstroom laten aanleggen via VakConnect", "description": "Voor kookplaat, werkplaats of zwaardere apparatuur: vind een passende elektricien.", "h1": "Krachtstroom aanvragen", "intro": ["Krachtstroom vraagt een goede beoordeling van je installatie en capaciteit.", "Via VakConnect beschrijf je je toepassing en locatie voor een passende match."], "signals": ["Nieuwe apparatuur vereist 3-fase", "Huidige aansluiting voldoet niet", "Plannen voor werkplaats of laadoplossing"], "causes": ["Toegenomen vermogensvraag", "Verouderde groepenkast", "Geen geschikte bekabeling"], "actions": ["Voorwaarden en capaciteit controleren", "Krachtgroep en bekabeling realiseren", "Aansluiting testen"], "materials": ["Kabeldoorsnede en beveiliging zijn cruciaal", "Afstand en route beïnvloeden kosten"], "delay": ["Apparatuur kan niet veilig gebruikt worden", "Latere aanpassingen kunnen duurder uitvallen"], "related": ["/elektricien", "/elektricien/groepenkast", "/verbouwing/keuken-verbouwen"], "faq": [["Is netverzwaring altijd nodig?", "Niet altijd; dat hangt af van de bestaande aansluiting."], ["Kan dit in bestaande woning?", "Ja, maar vereist vaak maatwerk."], ["Kan ik dit zelf aansluiten?", "Werk aan vaste installatie laat je uitvoeren door een vakman."]], "cta": "Vraag krachtstroom aan", "warning": true}),
  "kozijnen/kunststof-kozijnen": buildSubPage("kozijnen/kunststof-kozijnen", {"title": "Kunststof kozijnen via VakConnect", "description": "Lees de aandachtspunten van kunststof kozijnen en vind een passende specialist.", "h1": "Kunststof kozijnen laten plaatsen", "intro": ["Kunststof kozijnen zijn populair door onderhoudsgemak.", "Via VakConnect kun je je wensen en woningtype gericht delen."], "signals": ["Huidige kozijnen vragen veel onderhoud", "Tochtklachten", "Wens voor betere isolatie"], "causes": ["Verouderde kozijnen", "Onvoldoende kierdichting", "Slijtage van beslag"], "actions": ["Inmeten en productkeuze", "Demonteren en plaatsen", "Afwerken en afstellen"], "materials": ["Profielopbouw en glaskeuze beïnvloeden prestaties", "Kleur en afwerking bepalen uitstraling"], "delay": ["Energieverlies en tocht blijven bestaan", "Onderhoud aan oude kozijnen loopt op"], "related": ["/kozijnen", "/kozijnen/kozijnen-vervangen", "/kozijnen/ramen-en-deuren"], "faq": [["Hoe onderhoudsarm is kunststof?", "Onderhoud blijft nodig, maar meestal minder intensief dan hout."], ["Past kunststof bij oudere woningen?", "Vaak wel met passende stijlkeuze."], ["Kan ik alleen benedenverdieping doen?", "Ja, gefaseerde vervanging is mogelijk."]], "cta": "Start je aanvraag voor kunststof kozijnen"}),
  "kozijnen/houten-kozijnen": buildSubPage("kozijnen/houten-kozijnen", {"title": "Houten kozijnen laten plaatsen of herstellen", "description": "Voor uitstraling en herstelbaarheid: vind via VakConnect een specialist voor houten kozijnen.", "h1": "Houten kozijnen aanvragen", "intro": ["Houten kozijnen bieden karakter en zijn goed te onderhouden bij tijdig schilderwerk.", "Via VakConnect krijg je hulp van een passende specialist."], "signals": ["Bladderende verf en zachte plekken", "Klemmen van ramen", "Terugkerende tocht"], "causes": ["Vochtbelasting", "Uitgesteld onderhoud", "Verouderde onderdelen"], "actions": ["Conditie-inspectie", "Herstel of vervanging bepalen", "Plaatsen en afwerken"], "materials": ["Houtsoort en afwerking bepalen levensduur", "Regelmatig schilderwerk blijft belangrijk"], "delay": ["Beginnende houtschade kan versnellen", "Herstel wordt later omvangrijker"], "related": ["/kozijnen", "/schilder/kozijnen-schilderen", "/kozijnen/kozijnen-vervangen"], "faq": [["Is herstel vaak mogelijk?", "Ja, afhankelijk van de mate van aantasting."], ["Hoe vaak onderhoudsschilderen?", "Dat verschilt per ligging en afwerking."], ["Kan vervanging per kozijn?", "Ja, je hoeft niet alles tegelijk te doen."]], "cta": "Vraag hulp voor houten kozijnen"}),
  "kozijnen/aluminium-kozijnen": buildSubPage("kozijnen/aluminium-kozijnen", {"title": "Aluminium kozijnen via VakConnect", "description": "Voor slanke profielen en sterke constructie: vind een passende kozijnspecialist.", "h1": "Aluminium kozijnen laten plaatsen", "intro": ["Aluminium kozijnen zijn sterk en passen goed bij moderne uitstraling.", "Via VakConnect kun je jouw project gericht laten beoordelen."], "signals": ["Wens voor strakke profielen", "Vervanging van oude kozijnen", "Combinatie met grotere glasvlakken"], "causes": ["Renovatie of esthetische upgrade", "Verbetering van comfort", "Slijtage van bestaande kozijnen"], "actions": ["Inmeten en systeemkeuze", "Plaatsing en afwerking", "Controle op sluiting en luchtdichtheid"], "materials": ["Profielsysteem en glas bepalen prestaties", "Thermische onderbreking is belangrijk voor comfort"], "delay": ["Woningverbetering blijft uit", "Planningen met andere werkzaamheden schuiven door"], "related": ["/kozijnen", "/kozijnen/ramen-en-deuren", "/verbouwing/uitbouw"], "faq": [["Zijn aluminium kozijnen onderhoudsarm?", "Ja, doorgaans met beperkte periodieke reiniging."], ["Kunnen ze in bestaande bouw?", "Ja, met goede inmeting en aansluiting."], ["Is maatwerk mogelijk?", "Ja, vaak in verschillende afmetingen en kleuren."]], "cta": "Vind een specialist voor aluminium kozijnen"}),
  "kozijnen/kozijnen-vervangen": buildSubPage("kozijnen/kozijnen-vervangen", {"title": "Kozijnen vervangen via VakConnect", "description": "Bepaal wanneer vervanging logisch is en vind een passende vakman via VakConnect.", "h1": "Kozijnen laten vervangen", "intro": ["Soms is vervangen efficiënter dan steeds repareren.", "Via VakConnect kun je jouw huidige situatie laten beoordelen door een specialist."], "signals": ["Terugkerende tocht", "Houtrot of vervorming", "Slecht sluitwerk"], "causes": ["Leeftijd en slijtage", "Vochtproblemen", "Onvoldoende onderhoud"], "actions": ["Conditie-opname", "Materiaal- en glasadvies", "Vervangen en afwerken"], "materials": ["Kunststof, hout en aluminium hebben verschillende onderhoudsprofielen", "Glaskeuze beïnvloedt isolatie"], "delay": ["Comfort en energievraag blijven ongunstig", "Schade aan omliggende afwerking kan toenemen"], "related": ["/kozijnen", "/kozijnen/kunststof-kozijnen", "/kozijnen/houten-kozijnen"], "faq": [["Wanneer is vervangen beter dan herstellen?", "Bij structurele slijtage of terugkerende problemen."], ["Kan ik dit combineren met nieuw glas?", "Ja, dat is vaak logisch."], ["Hoe bereid ik me voor?", "Beschrijf aantal kozijnen, afmetingen en huidige klachten."]], "cta": "Plaats je aanvraag voor kozijnvervanging"}),
  "kozijnen/ramen-en-deuren": buildSubPage("kozijnen/ramen-en-deuren", {"title": "Ramen en deuren laten vernieuwen via VakConnect", "description": "Vind een passende specialist voor ramen en deuren binnen je kozijnproject.", "h1": "Ramen en deuren vernieuwen", "intro": ["Ramen en deuren bepalen gebruiksgemak, isolatie en veiligheid.", "Via VakConnect beschrijf je je wensen en huidige situatie voor een passende specialist."], "signals": ["Slecht sluitende ramen of deuren", "Tocht en geluidsoverlast", "Beschadigd beslag of sluitingen"], "causes": ["Slijtage van bewegende delen", "Verouderde systemen", "Vervorming van bestaande kozijnen"], "actions": ["Inspectie van draaipunten en beslag", "Vervangen of afstellen van onderdelen", "Combinatie met nieuw glas of kozijnwerk"], "materials": ["Type scharnier en slot hangt af van toepassing", "Materiaalkeuze beïnvloedt onderhoud"], "delay": ["Gebruiksgemak en veiligheid nemen af", "Kans op vervolgschade groeit"], "related": ["/kozijnen", "/kozijnen/kozijnen-vervangen", "/schilder/deuren-schilderen"], "faq": [["Kan alleen beslag vervangen worden?", "Soms wel, afhankelijk van de staat."], ["Is volledige vervanging nodig bij tocht?", "Niet altijd; goede inspectie bepaalt de beste stap."], ["Kan dit per verdieping?", "Ja, gefaseerde aanpak is mogelijk."]], "cta": "Vraag een specialist voor ramen en deuren"}),
  "badkamer/renovatie": buildSubPage("badkamer/renovatie", {"title": "Badkamerrenovatie via VakConnect", "description": "Plan je badkamerrenovatie met duidelijke keuzes en vind een passende specialist.", "h1": "Badkamerrenovatie starten", "intro": ["Een renovatie vraagt afstemming tussen sloop, installatie en afwerking.", "Via VakConnect kun je je wensen helder bundelen in één aanvraag."], "signals": ["Verouderde uitstraling", "Lekkages of schimmel", "Onpraktische indeling"], "causes": ["Slijtage", "Achterhaalde installatie", "Gebrekkige ventilatie"], "actions": ["Situatie opnemen", "Nieuwe indeling en techniek bepalen", "Uitvoeren en afwerken"], "materials": ["Tegels, sanitair en kranen bepalen stijl en budget", "Vochtbestendige materialen verlengen levensduur"], "delay": ["Vocht- en schimmelproblemen kunnen verergeren", "Renovatie wordt later vaak omvangrijker"], "related": ["/badkamer", "/loodgieter", "/elektricien"], "faq": [["Moet alles eruit?", "Niet altijd; deelrenovatie is ook mogelijk."], ["Kan ik eigen producten kiezen?", "Ja, benoem dit in de aanvraag."], ["Welke informatie helpt?", "Maten, foto’s en gewenste indeling."]], "cta": "Start je badkamerrenovatie"}),
  "badkamer/tegelen": buildSubPage("badkamer/tegelen", {"title": "Badkamer tegelen via VakConnect", "description": "Voor wand- en vloertegels in badkamer: vind een passende specialist.", "h1": "Badkamer laten tegelen", "intro": ["Tegelwerk vraagt een vlakke ondergrond en zorgvuldige afwerking.", "Via VakConnect vraag je eenvoudig een specialist aan voor nieuw of vervangend tegelwerk."], "signals": ["Loslatende tegels", "Gebarsten voegen", "Verouderde uitstraling"], "causes": ["Vocht en beweging in ondergrond", "Verouderde lijm of voeg", "Onvoldoende waterdichting"], "actions": ["Ondergrond controleren", "Tegels plaatsen en voegen", "Aansluitingen netjes afwerken"], "materials": ["Formaat en type tegel beïnvloeden verwerking", "Kleur en voegbreedte bepalen het eindbeeld"], "delay": ["Vocht kan achter tegelwerk trekken", "Herstel wordt later intensiever"], "related": ["/badkamer", "/badkamer/renovatie", "/badkamer/inloopdouche"], "faq": [["Kan over bestaande tegels heen?", "Soms, afhankelijk van ondergrond en hoogte."], ["Welke tegel is onderhoudsvriendelijk?", "Dat hangt af van oppervlak en gebruik."], ["Is antislip nodig op vloer?", "In natte zones is dat vaak verstandig."]], "cta": "Vraag badkamer-tegelwerk aan"}),
  "badkamer/sanitair": buildSubPage("badkamer/sanitair", {"title": "Badkamer sanitair laten vervangen via VakConnect", "description": "Van wastafel tot doucheopstelling: vind een passende specialist.", "h1": "Sanitair in badkamer laten plaatsen", "intro": ["Goed sanitairwerk combineert waterdichte montage met functionele indeling.", "Via VakConnect beschrijf je je wensen voor een passende specialist."], "signals": ["Lekkende aansluitingen", "Verouderde set-up", "Wens voor comfortupgrade"], "causes": ["Slijtage", "Slechte oude montage", "Aanpassing van indeling"], "actions": ["Demonteren oud sanitair", "Aansluiten nieuw sanitair", "Afstellen en testen"], "materials": ["Maatvoering en aansluitpunten bepalen productkeuze", "Kwaliteit van kranen en afvoeren beïnvloedt levensduur"], "delay": ["Lekkagekans blijft bestaan", "Gebruiksgemak blijft beperkt"], "related": ["/badkamer", "/loodgieter/sanitair", "/badkamer/complete-badkamer"], "faq": [["Kan ik alleen douche of wastafel doen?", "Ja, deelvervanging is gebruikelijk."], ["Moet leidingwerk aangepast worden?", "Dat hangt af van nieuwe opstelling."], ["Kan dit samen met tegelwerk?", "Ja, vaak worden die werkzaamheden gecombineerd."]], "cta": "Start je aanvraag voor badkamersanitair"}),
  "badkamer/inloopdouche": buildSubPage("badkamer/inloopdouche", {"title": "Inloopdouche realiseren via VakConnect", "description": "Inloopdouche plannen? Vind een passende specialist via VakConnect.", "h1": "Inloopdouche laten maken", "intro": ["Een inloopdouche vraagt aandacht voor afschot, afvoer en waterdichting.", "Via VakConnect kun je jouw badkamer laten beoordelen door een passende professional."], "signals": ["Wens voor drempelloze douche", "Onpraktische oude doucheopstelling", "Water blijft staan"], "causes": ["Verouderde indeling", "Onvoldoende afvoeroplossing", "Slijtage in bestaande douchezone"], "actions": ["Technische haalbaarheid checken", "Vloer en afvoer aanpassen", "Douchezone afwerken"], "materials": ["Type drain en wandafwerking bepalen onderhoud", "Antislip en reinigbaarheid zijn belangrijke keuzes"], "delay": ["Bestaande doucheproblemen blijven terugkomen", "Later aanpassen kan meer breekwerk vragen"], "related": ["/badkamer", "/badkamer/tegelen", "/loodgieter/leidingwerk"], "faq": [["Past een inloopdouche in elke badkamer?", "Niet altijd; maat en afvoerhoogte zijn bepalend."], ["Is extra ventilatie nodig?", "Vaak is goede ventilatie sterk aan te raden."], ["Kan dit zonder volledige renovatie?", "Soms wel, afhankelijk van bestaande situatie."]], "cta": "Vraag een specialist voor inloopdouche"}),
  "badkamer/complete-badkamer": buildSubPage("badkamer/complete-badkamer", {"title": "Complete badkamer vernieuwen via VakConnect", "description": "Voor een complete badkameraanpak: vind een passende specialist via VakConnect.", "h1": "Complete badkamer laten vernieuwen", "intro": ["Bij een complete badkamer komen meerdere disciplines samen.", "Via VakConnect kun je alles in één overzichtelijke aanvraag beschrijven."], "signals": ["Badkamer is technisch en visueel verouderd", "Meerdere onderdelen moeten tegelijk aangepakt", "Wens voor nieuwe indeling en comfort"], "causes": ["Leeftijd van installaties", "Opstapeling van kleine gebreken", "Nieuwe woonwensen"], "actions": ["Inventarisatie en planvorming", "Coördinatie van uitvoering", "Oplevering en controle"], "materials": ["Combinatie van tegelwerk, sanitair en installatiemateriaal", "Afwerkingsniveau bepaalt tijd en budget"], "delay": ["Kleine problemen stapelen op", "Toekomstige renovatie wordt complexer"], "related": ["/badkamer", "/badkamer/renovatie", "/verbouwing/woning-renoveren"], "faq": [["Hoe gedetailleerd moet mijn aanvraag zijn?", "Globale wensen plus foto’s zijn een goed startpunt."], ["Kan ik fases kiezen?", "Ja, sommige projecten worden gefaseerd uitgevoerd."], ["Moet ik alles al gekozen hebben?", "Nee, materiaalkeuzes kunnen later verfijnd worden."]], "cta": "Plaats je complete badkamer-aanvraag"}),
  "isolatie/dakisolatie": buildSubPage("isolatie/dakisolatie", {"title": "Dakisolatie via VakConnect", "description": "Beperk warmteverlies met dakisolatie en vind een passende specialist.", "h1": "Dakisolatie laten aanbrengen", "intro": ["Dakisolatie is vaak een effectieve stap bij warmteverlies via bovenste bouwlaag.", "Via VakConnect vraag je een specialist aan op basis van jouw woningtype."], "signals": ["Snel afkoelende bovenverdieping", "Hoge stookvraag", "Koude trek op zolder"], "causes": ["Onvoldoende bestaande isolatie", "Verouderde dakopbouw", "Kieren en zwakke aansluitingen"], "actions": ["Inspectie van opbouw", "Kiezen van passende methode", "Aanbrengen en afwerken"], "materials": ["Binnen- of buitenzijde isoleren hangt af van daktype", "Vochtgedrag en ventilatie zijn belangrijke randvoorwaarden"], "delay": ["Energieverlies blijft structureel", "Comfort op verdieping blijft laag"], "related": ["/isolatie", "/dakdekker/dakrenovatie", "/verbouwing/zolder-verbouwen"], "faq": [["Moet dak open voor isolatie?", "Dat hangt af van gekozen methode."], ["Kan dit tijdens renovatie?", "Ja, combineren is vaak efficiënt."], ["Wanneer is advies nodig?", "Bij oudere daken is een goede inspectie extra belangrijk."]], "cta": "Vraag dakisolatie aan"}),
  "isolatie/spouwmuurisolatie": buildSubPage("isolatie/spouwmuurisolatie", {"title": "Spouwmuurisolatie aanvragen via VakConnect", "description": "Voor bestaande woningen met spouw: vind een passende specialist.", "h1": "Spouwmuurisolatie laten uitvoeren", "intro": ["Spouwmuurisolatie kan comfort verbeteren zonder grote verbouwing.", "Via VakConnect kun je je woninggegevens delen voor een passende specialist."], "signals": ["Koude buitenmuren", "Tochtbeleving", "Hoge energievraag"], "causes": ["Lege of verouderde spouw", "Ongelijkmatige isolatievulling", "Natte plekken bij gebrekkige gevelstaat"], "actions": ["Geschiktheid van spouw controleren", "Materiaal inblazen", "Resultaat en afwerking controleren"], "materials": ["Type isolatievulling hangt af van spouwconditie", "Vochtbelasting van gevel moet worden meegewogen"], "delay": ["Warmteverlies blijft doorgaan", "Mogelijke vochtissues blijven onduidelijk"], "related": ["/isolatie", "/isolatie/gevelisolatie", "/verbouwing/woning-renoveren"], "faq": [["Is elke spouw geschikt?", "Nee, eerst wordt de spouwconditie beoordeeld."], ["Hoe lang duurt dit meestal?", "Vaak korter dan grotere renovaties."], ["Moet ik binnen iets voorbereiden?", "Meestal is buitenzijde het belangrijkste werkgebied."]], "cta": "Start je aanvraag voor spouwmuurisolatie"}),
  "isolatie/vloerisolatie": buildSubPage("isolatie/vloerisolatie", {"title": "Vloerisolatie via VakConnect", "description": "Voor koud aanvoelende vloeren en comfortverbetering: vind een passende specialist.", "h1": "Vloerisolatie laten aanbrengen", "intro": ["Vloerisolatie helpt bij comfort in leefruimtes op de begane grond.", "Via VakConnect kun je snel een specialist vinden die past bij je woning."], "signals": ["Koude vloer in winter", "Tocht langs plinten", "Vochtige kruipruimte"], "causes": ["Ongeïsoleerde vloer", "Koude lucht uit kruipruimte", "Vochtbelasting"], "actions": ["Inspectie van kruipruimte", "Selectie van isolatiemethode", "Aanbrengen en controle"], "materials": ["Bereikbaarheid bepaalt beschikbare technieken", "Vochtbestendigheid van materiaal is essentieel"], "delay": ["Comfortverlies blijft bestaan", "Stookkosten blijven relatief hoog"], "related": ["/isolatie", "/isolatie/kruipruimte-isolatie", "/verbouwing/woning-renoveren"], "faq": [["Heb ik een kruipruimte nodig?", "Dat is vaak nodig voor veel methoden."], ["Is vocht eerst een probleem?", "Ja, vochtbron moet worden meegenomen in advies."], ["Kan dit per deel van de woning?", "Soms, afhankelijk van vloeropbouw."]], "cta": "Vraag vloerisolatie aan"}),
  "isolatie/gevelisolatie": buildSubPage("isolatie/gevelisolatie", {"title": "Gevelisolatie plannen via VakConnect", "description": "Voor gevelisolatie aan buitenzijde of binnenzijde: vind een passende specialist.", "h1": "Gevelisolatie laten uitvoeren", "intro": ["Gevelisolatie is vaak onderdeel van een grotere verduurzamingsstap.", "Via VakConnect kun je je situatie laten beoordelen op haalbaarheid en aanpak."], "signals": ["Koude wandoppervlakken", "Hoge warmteverliezen via gevel", "Renovatieplannen van buitengevel"], "causes": ["Onvoldoende isolerende schil", "Verouderde gevelafwerking", "Constructieve koudebruggen"], "actions": ["Opname van gevelconditie", "Keuze van systeem en afwerking", "Uitvoering en aansluiting op details"], "materials": ["Systeemkeuze beïnvloedt uitstraling en onderhoud", "Aansluiting rond kozijnen vraagt nauwkeurigheid"], "delay": ["Verduurzaming blijft achter", "Later combineren met renovatie wordt lastiger"], "related": ["/isolatie", "/kozijnen/kozijnen-vervangen", "/verbouwing/uitbouw"], "faq": [["Is vergunning soms nodig?", "Dat kan per situatie verschillen."], ["Kan gevelisolatie met kozijnvervanging samen?", "Ja, die combinatie is vaak logisch."], ["Moet de hele gevel tegelijk?", "Niet altijd, gefaseerd kan soms ook."]], "cta": "Beschrijf je gevelisolatieklus"}),
  "verbouwing/aanbouw": buildSubPage("verbouwing/aanbouw", {"title": "Aanbouw realiseren via VakConnect", "description": "Meer woonruimte met een aanbouw? Vind een passende specialist via VakConnect.", "h1": "Aanbouw laten uitvoeren", "intro": ["Een aanbouw verandert gebruiksruimte en vraagt zorgvuldige voorbereiding.", "Via VakConnect kun je je project gericht voorleggen aan een passende professional."], "signals": ["Structureel ruimtegebrek", "Wens voor grotere leefkeuken", "Noodzaak voor extra werk- of leefruimte"], "causes": ["Gezinssituatie verandert", "Functionele wensen groeien", "Huidige indeling schiet tekort"], "actions": ["Scope en haalbaarheid bepalen", "Bouwkundige uitvoering plannen", "Afbouw en aansluiting op bestaande woning"], "materials": ["Constructiemethode en afwerking bepalen planning", "Materiaalkeuze beïnvloedt uitstraling en onderhoud"], "delay": ["Wooncomfort blijft achter", "Combinatie met andere renovaties wordt lastiger"], "related": ["/verbouwing", "/verbouwing/uitbouw", "/elektricien/krachtstroom"], "faq": [["Is een vergunning altijd nodig?", "Dat hangt af van type en omvang."], ["Kan ik gefaseerd bouwen?", "Soms wel, afhankelijk van ontwerp."], ["Welke info in aanvraag?", "Gewenste afmetingen, functie en foto’s van huidige situatie."]], "cta": "Start je aanvraag voor aanbouw"}),
  "verbouwing/uitbouw": buildSubPage("verbouwing/uitbouw", {"title": "Uitbouw plannen via VakConnect", "description": "Voor uitbouw van woonkamer of keuken: vind een passende specialist.", "h1": "Uitbouw laten realiseren", "intro": ["Met een uitbouw vergroot je bestaande ruimte zonder te verhuizen.", "Via VakConnect leg je wensen en randvoorwaarden direct vast."], "signals": ["Te kleine leefruimte", "Wens voor open woonkeuken", "Ruimtegebrek aan tuinzijde"], "causes": ["Huidige plattegrond beperkt", "Nieuwe leefwensen", "Combinatie met renovatieplan"], "actions": ["Opname en advies", "Bouwkundige uitvoering", "Installatiewerk en afwerking"], "materials": ["Gevelmaterialen en dakopbouw beïnvloeden eindbeeld", "Aansluiting op bestaande constructie is cruciaal"], "delay": ["Ruimteprobleem blijft bestaan", "Project kan duurder uitvallen door latere start"], "related": ["/verbouwing", "/verbouwing/aanbouw", "/verbouwing/keuken-verbouwen"], "faq": [["Is uitbouw iets anders dan aanbouw?", "De termen overlappen vaak; invulling verschilt per project."], ["Kan dit met bewoonde woning?", "Ja, maar planning is belangrijk."], ["Moet ik al een definitief ontwerp hebben?", "Nee, een duidelijke wensomschrijving is genoeg om te starten."]], "cta": "Vraag een specialist voor uitbouw"}),
  "verbouwing/zolder-verbouwen": buildSubPage("verbouwing/zolder-verbouwen", {"title": "Zolder verbouwen via VakConnect", "description": "Maak van je zolder een bruikbare ruimte met hulp van een passende specialist.", "h1": "Zolder laten verbouwen", "intro": ["Een zolder kan veel extra woonwaarde bieden bij slimme indeling.", "Via VakConnect kun je je plannen voor isolatie, afwerking en indeling combineren."], "signals": ["Onbenutte opslagzolder", "Te weinig slaapkamers of werkplek", "Comfortproblemen op bovenste verdieping"], "causes": ["Gebrek aan isolatie", "Onpraktische indeling", "Onvoldoende licht of elektra"], "actions": ["Ruimte-indeling bepalen", "Bouwkundige en installatietechnische aanpassingen", "Afbouw voor dagelijks gebruik"], "materials": ["Isolatie, wandafwerking en vloerkeuze bepalen comfort", "Ventilatie en elektra moeten worden meegenomen"], "delay": ["Potentiële woonruimte blijft onbenut", "Latere verbouwing kan complexer worden"], "related": ["/verbouwing", "/isolatie/dakisolatie", "/elektricien/verlichting"], "faq": [["Kan ik direct een extra kamer maken?", "Vaak wel, afhankelijk van hoogte en indeling."], ["Moet isolatie mee?", "In veel gevallen wel voor comfort."], ["Welke voorbereiding helpt?", "Foto’s, maten en gewenste functie van de ruimte."]], "cta": "Plaats je zolderverbouwing-aanvraag"}),
  "verbouwing/woning-renoveren": buildSubPage("verbouwing/woning-renoveren", {"title": "Woning renoveren via VakConnect", "description": "Voor renovatie in fases of totaalproject: vind een passende specialist.", "h1": "Woning laten renoveren", "intro": ["Bij woningrenovatie draait het om volgorde, techniek en afwerking.", "Via VakConnect kun je je project helder kaderen voor een passende professional."], "signals": ["Meerdere verouderde bouwdelen", "Installaties voldoen niet meer", "Comfort en energieprestatie blijven achter"], "causes": ["Lang uitgesteld onderhoud", "Veranderde woonwensen", "Technische veroudering"], "actions": ["Prioriteiten stellen", "Fasering en planning uitwerken", "Uitvoeren met controle per stap"], "materials": ["Keuzes per ruimte beïnvloeden totale planning", "Combinatie met isolatie en kozijnen kan logisch zijn"], "delay": ["Onderhoudsachterstand groeit", "Kosten nemen toe door stapeling van problemen"], "related": ["/verbouwing", "/isolatie", "/kozijnen"], "faq": [["Kan renovatie in delen?", "Ja, gefaseerde aanpak is vaak praktisch."], ["Wat vermeld ik als start?", "Belangrijkste problemen, prioriteiten en foto’s."], ["Wanneer meerdere vakgebieden combineren?", "Bij projecten met installaties en bouwkundige aanpassingen."]], "cta": "Start je woningrenovatie-aanvraag"}),
  "verbouwing/keuken-verbouwen": buildSubPage("verbouwing/keuken-verbouwen", {"title": "Keuken verbouwen via VakConnect", "description": "Nieuwe keukenindeling of complete keukenverbouwing? Vind een passende specialist.", "h1": "Keuken laten verbouwen", "intro": ["Een keukenverbouwing raakt vaak elektra, water en afwerking tegelijk.", "Via VakConnect maak je jouw wensen concreet voor een passende specialist."], "signals": ["Verouderde opstelling", "Te weinig werk- of opbergruimte", "Wens voor andere apparatuur"], "causes": ["Nieuwe gezinssituatie", "Technische beperkingen van oude keuken", "Slijtage en ouderdom"], "actions": ["Inventarisatie en maatvoering", "Leidingwerk en elektra aanpassen", "Plaatsing en afwerking"], "materials": ["Keuze van werkblad en fronten beïnvloedt onderhoud", "Aansluitpunten moeten passen bij apparatuur"], "delay": ["Gebruiksgemak blijft beperkt", "Extra kosten bij onverwachte technische knelpunten"], "related": ["/verbouwing", "/loodgieter/leidingwerk", "/elektricien/stopcontacten"], "faq": [["Kan ik bestaande delen hergebruiken?", "Soms wel, afhankelijk van staat en maatvoering."], ["Moet alles in één keer?", "Niet per se, fases zijn mogelijk."], ["Welke gegevens zijn nuttig?", "Maten, foto’s en gewenste apparatuur."]], "cta": "Vraag een specialist voor keukenverbouwing"}),
  "loodgieter/afvoer": buildSubPage("loodgieter/afvoer", {"title": "Afvoerproblemen oplossen via VakConnect", "description": "Vind een passende loodgieter voor afvoerherstel en onderhoud.", "h1": "Afvoer laten controleren of herstellen", "intro": ["Afvoerproblemen ontstaan vaak geleidelijk en worden dan plots ernstig.", "Via VakConnect vraag je gericht hulp aan met de juiste intake-informatie."], "signals": ["Langzaam wegstromend water", "Geurhinder uit afvoer", "Regelmatige terugslag"], "causes": ["Ophoping in leidingtraject", "Verzakte delen", "Onjuiste helling"], "actions": ["Inspectie en lokalisatie", "Reinigen of deels vervangen", "Doorstroom controleren"], "materials": ["Bereikbaarheid van leidingen beïnvloedt aanpak", "Soms is camera-inspectie nodig"], "delay": ["Kans op verstopping en waterschade neemt toe", "Hygiëne en gebruiksgemak verslechteren"], "related": ["/loodgieter", "/loodgieter/verstopping", "/dakdekker/dakgoot"], "faq": [["Wanneer specialist inschakelen?", "Bij terugkerende klachten of volledige blokkade."], ["Helpt periodiek onderhoud?", "Ja, preventieve controle kan grotere problemen voorkomen."], ["Wat vermeld ik in mijn aanvraag?", "Locatie, frequentie en aard van het probleem."]], "cta": "Plaats je aanvraag voor afvoerproblemen"}),
  "isolatie/kruipruimte-isolatie": buildSubPage("isolatie/kruipruimte-isolatie", {"title": "Kruipruimte isolatie via VakConnect", "description": "Voor koude vloeren en vochtige kruipruimtes: vind een passende specialist.", "h1": "Kruipruimte laten isoleren", "intro": ["Een koude of vochtige kruipruimte beïnvloedt comfort op de begane grond.", "Via VakConnect kun je een passende specialist vinden voor inspectie en uitvoering."], "signals": ["Koude vloer", "Vochtige lucht", "Schimmelgeur in woning"], "causes": ["Ongeïsoleerde bodem of vloer", "Vochtbelasting vanuit bodem", "Onvoldoende ventilatie"], "actions": ["Toegankelijkheid controleren", "Geschikt isolatiesysteem kiezen", "Aanbrengen en naloop"], "materials": ["Type isolatie hangt af van vocht en hoogte", "Vochtbestendige oplossingen zijn vaak noodzakelijk"], "delay": ["Comfortproblemen blijven bestaan", "Vochtbelasting kan andere bouwdelen raken"], "related": ["/isolatie", "/isolatie/vloerisolatie", "/verbouwing/woning-renoveren"], "faq": [["Is kruipruimte altijd toegankelijk?", "Niet altijd, dit wordt eerst beoordeeld."], ["Kan bodemisolatie een optie zijn?", "Ja, afhankelijk van situatie."], ["Helpt dit tegen tocht?", "Vaak wel, mits juist uitgevoerd."]], "cta": "Vraag kruipruimte-isolatie aan"}),
  "badkamer/ventilatie": buildSubPage("badkamer/ventilatie", {"title": "Badkamerventilatie verbeteren via VakConnect", "description": "Vocht en schimmel in badkamer? Vind een passende specialist voor ventilatie-oplossingen.", "h1": "Badkamerventilatie laten verbeteren", "intro": ["Goede ventilatie voorkomt vochtophoping en verlengt de levensduur van afwerking.", "Via VakConnect kun je gericht hulp aanvragen voor beoordeling en verbetering."], "signals": ["Beslagen spiegels die lang nat blijven", "Schimmelvorming in voegen", "Muffe geur"], "causes": ["Onvoldoende luchtafvoer", "Verouderde ventilator", "Onjuiste gebruiksinstelling"], "actions": ["Ventilatiecapaciteit beoordelen", "Aanpassen of vervangen van ventilatiecomponenten", "Afstemming met badkamerindeling"], "materials": ["Type ventilatiesysteem hangt af van woningopbouw", "Vochtbestendige componenten zijn belangrijk"], "delay": ["Schimmel en vochtbelasting nemen toe", "Afwerking slijt sneller"], "related": ["/badkamer", "/badkamer/renovatie", "/elektricien/verlichting"], "faq": [["Is ventilatie bij renovatie verplicht?", "Eisen verschillen per situatie; goede ventilatie is in elk geval sterk aan te raden."], ["Kan bestaande ventilator blijven?", "Dat hangt af van capaciteit en staat."], ["Wat zet ik in mijn aanvraag?", "Type ruimte, klachten en huidige ventilatievoorziening."]], "cta": "Start je aanvraag voor badkamerventilatie"}),
};

export const serviceMainSlugs = Object.keys(serviceMainPages);
export const serviceSubSlugs = Object.keys(serviceSubPages).map((slug) => {
  const [vakgebied, subdienst] = slug.split("/");
  return { vakgebied, subdienst };
});

export function getServiceMainPage(slug: string) {
  return serviceMainPages[slug];
}

export function getServiceSubPage(vakgebied: string, subdienst: string) {
  return serviceSubPages[`${vakgebied}/${subdienst}`];
}

export function getAllServiceRoutes() {
  return [
    ...serviceMainSlugs.map((slug) => `/${slug}`),
    ...Object.keys(serviceSubPages).map((slug) => `/${slug}`),
  ];
}
