alter table public.seo_locations
  add column if not exists tier text not null default 'C' check (tier in ('A', 'B', 'C')),
  add column if not exists content_profile jsonb not null default '{}'::jsonb;

alter table public.seo_local_pages
  add column if not exists quality_score integer not null default 0,
  add column if not exists duplicate_risk text not null default 'high' check (duplicate_risk in ('low', 'medium', 'high')),
  add column if not exists coverage_status text not null default 'none' check (coverage_status in ('none', 'limited', 'sufficient'));

create index if not exists seo_local_pages_quality_score_idx on public.seo_local_pages (quality_score);
create index if not exists seo_local_pages_duplicate_risk_idx on public.seo_local_pages (duplicate_risk);
create index if not exists seo_local_pages_coverage_status_idx on public.seo_local_pages (coverage_status);
create index if not exists seo_locations_tier_idx on public.seo_locations (tier);

create table if not exists public.seo_audit_log (
  id uuid primary key default gen_random_uuid(),
  seo_local_page_id uuid not null references public.seo_local_pages(id) on delete cascade,
  actor text not null,
  action text not null check (action in ('status_change', 'publish', 'unpublish')),
  previous_status text not null,
  new_status text not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.seo_audit_log enable row level security;

create policy "admins manage seo audit log"
  on public.seo_audit_log
  for all
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

insert into public.seo_locations (
  slug,
  name,
  province,
  region_label,
  tier,
  content_profile,
  intro_facts,
  local_characteristics,
  nearby_city_slugs,
  population_band,
  housing_notes,
  published,
  indexable,
  priority
)
values
  ('maastricht', 'Maastricht', 'Limburg', 'Zuid-Limburg', 'B', '{"urbanDensity":"gemiddeld","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Maastricht heeft gevarieerde woongebieden met verschillende bouwperioden.","Een duidelijke intake met bereikbaarheid en planning helpt bij lokale uitvoering."]'::jsonb, '["Combinatie van oudere bouw en renovatie vraagt zorgvuldige opname.","Toegang en logistiek verschillen per wijk en type woning."]'::jsonb, '["heerlen","sittard","roermond"]'::jsonb, 'middelgrote stad', 'Redactioneel profiel met focus op stedelijke en historische woningcontext.', true, true, 0.8),
  ('venlo', 'Venlo', 'Limburg', 'Noord-Limburg', 'C', '{"urbanDensity":"lager","buildingEraMix":"naoorlogse-mix","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Venlo heeft gevarieerde woonwijken met verschillende onderhoudsvragen.","Lokale uitvoering profiteert van duidelijke planning en toegangsinfo."]'::jsonb, '["Mix van bestaande bouw en nieuwere wijken vraagt contextspecifieke intake.","Parkeer- en materiaalrouting vooraf delen voorkomt vertraging."]'::jsonb, '["roermond","sittard","maastricht"]'::jsonb, 'regionale stad', 'Stad met regionale woningmix en uiteenlopende logistiek per buurt.', true, true, 0.64),
  ('roermond', 'Roermond', 'Limburg', 'Midden-Limburg', 'C', '{"urbanDensity":"lager","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Roermond combineert historische en nieuwere woongebieden.","Voor lokale klussen helpt het om woningcontext en planning concreet te maken."]'::jsonb, '["Bij oudere bouw zijn bestaande details vaak bepalend voor uitvoering.","Toegang en planning verschillen per wijk."]'::jsonb, '["venlo","sittard","maastricht"]'::jsonb, 'regionale stad', 'Regionale kern met historische en naoorlogse woningvoorraad.', true, true, 0.64),
  ('heerlen', 'Heerlen', 'Limburg', 'Zuid-Limburg', 'C', '{"urbanDensity":"lager","buildingEraMix":"gemengd","historicCore":false,"suburbanExpansion":false}'::jsonb, '["Heerlen heeft gevarieerde woonwijken met uiteenlopende bouwperioden.","Heldere intake ondersteunt lokale planning en uitvoering."]'::jsonb, '["Bestaande bouw en renovatie lopen door elkaar.","Toegang en bereikbaarheid verschillen per buurt."]'::jsonb, '["maastricht","sittard","venlo"]'::jsonb, 'regionale stad', 'Lokale context met mix van renovatie- en onderhoudsvraag.', true, true, 0.64),
  ('sittard', 'Sittard', 'Limburg', 'Zuid-Limburg', 'C', '{"urbanDensity":"lager","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Sittard heeft diverse woningtypen en bouwjaren.","Voor lokale matching helpt een complete intake."]'::jsonb, '["Historische kern en recente renovaties vragen maatwerk.","Praktische randvoorwaarden per locatie vooraf delen helpt."]'::jsonb, '["maastricht","heerlen","roermond"]'::jsonb, 'regionale stad', 'Kernstad met historische en gemengde woningstructuur.', true, true, 0.64),
  ('helmond', 'Helmond', 'Noord-Brabant', 'Zuidoost-Brabant', 'C', '{"urbanDensity":"lager","buildingEraMix":"naoorlogse-mix","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Helmond heeft verschillende woonwijken met uiteenlopende bouwperioden.","Lokale planning wordt sterker met duidelijke bereikbaarheid en scope."]'::jsonb, '["Mix van bestaande bouw en uitbreiding vraagt contextspecifieke aanpak.","Toegang en logistiek verschillen per wijk."]'::jsonb, '["eindhoven","oss","den-bosch"]'::jsonb, 'regionale stad', 'Regionale stad met naoorlogse en groeiwijken.', true, true, 0.64),
  ('oss', 'Oss', 'Noord-Brabant', 'Noordoost-Brabant', 'C', '{"urbanDensity":"lager","buildingEraMix":"naoorlogse-mix","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Oss heeft een gevarieerde woningmix.","Praktische intake over planning en toegang helpt lokale uitvoering."]'::jsonb, '["Woningtypes verschillen per wijk.","Bereikbaarheid en materiaalrouting vroeg afstemmen helpt."]'::jsonb, '["den-bosch","nijmegen","waalwijk"]'::jsonb, 'regionale stad', 'Regionale woningcontext met mix van onderhoud en renovatie.', true, true, 0.64),
  ('roosendaal', 'Roosendaal', 'Noord-Brabant', 'West-Brabant', 'C', '{"urbanDensity":"lager","buildingEraMix":"gemengd","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Roosendaal kent uiteenlopende woningtypen.","Lokale matching profiteert van complete aanvraaginformatie."]'::jsonb, '["Renovatie en onderhoudsvragen verschillen per buurt.","Toegangssituatie en planning vooraf delen helpt."]'::jsonb, '["bergen-op-zoom","etten-leur","breda"]'::jsonb, 'regionale stad', 'West-Brabantse stad met gevarieerde woningvoorraad.', true, true, 0.64),
  ('bergen-op-zoom', 'Bergen op Zoom', 'Noord-Brabant', 'West-Brabant', 'C', '{"urbanDensity":"lager","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Bergen op Zoom combineert historische delen en nieuwere wijken.","Heldere intake helpt bij lokale planning."]'::jsonb, '["Historische kern vraagt soms extra voorbereiding.","Bereikbaarheid en werkvensters verschillen per buurt."]'::jsonb, '["roosendaal","etten-leur","breda"]'::jsonb, 'regionale stad', 'Historische kernstad met regionale woningmix.', true, true, 0.64),
  ('oosterhout', 'Oosterhout', 'Noord-Brabant', 'West-Brabant', 'C', '{"urbanDensity":"lager","buildingEraMix":"gemengd","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Oosterhout heeft uiteenlopende woningcontexten.","Lokale uitvoering vraagt heldere intake en planning."]'::jsonb, '["Bestaande bouw en uitbreiding komen naast elkaar voor.","Logistieke details vooraf delen voorkomt ruis."]'::jsonb, '["breda","waalwijk","tilburg"]'::jsonb, 'regionale stad', 'Regionale stad met mix van bestaande bouw en groeiwijken.', true, true, 0.64),
  ('etten-leur', 'Etten-Leur', 'Noord-Brabant', 'West-Brabant', 'C', '{"urbanDensity":"lager","buildingEraMix":"gemengd","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Etten-Leur heeft een mix van woonwijken.","Duidelijke aanvraagdetails verbeteren lokale matching."]'::jsonb, '["Woningcontext verschilt per wijk.","Toegang en planning per locatie vooraf benoemen helpt."]'::jsonb, '["breda","roosendaal","bergen-op-zoom"]'::jsonb, 'regionale stad', 'Stad met gevarieerde woningtypologie in West-Brabant.', true, true, 0.64),
  ('waalwijk', 'Waalwijk', 'Noord-Brabant', 'Midden-Brabant', 'C', '{"urbanDensity":"lager","buildingEraMix":"naoorlogse-mix","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Waalwijk heeft diverse woongebieden.","Lokale planning profiteert van concrete intake."]'::jsonb, '["Oudere en recentere woningen vragen verschillende aanpak.","Logistiek en toegang per straat vooraf meenemen helpt."]'::jsonb, '["tilburg","den-bosch","oosterhout"]'::jsonb, 'regionale stad', 'Midden-Brabantse stad met gemengde woningvoorraad.', true, true, 0.64),
  ('gouda', 'Gouda', 'Zuid-Holland', 'Midden-Holland', 'B', '{"urbanDensity":"gemiddeld","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Gouda combineert historische kern en omliggende woonwijken.","Lokale intake met context en planning helpt betere uitvoering."]'::jsonb, '["Historische en naoorlogse bouw lopen door elkaar.","Bereikbaarheid en parkeersituatie verschillen per buurt."]'::jsonb, '["zoetermeer","capelle-aan-den-ijssel","rotterdam"]'::jsonb, 'middelgrote stad', 'Regionale stad met historische kern en gevarieerde woonwijken.', true, true, 0.8),
  ('zoetermeer', 'Zoetermeer', 'Zuid-Holland', 'Randstad', 'B', '{"urbanDensity":"gemiddeld","buildingEraMix":"nieuwbouw-groei","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Zoetermeer heeft een mix van woonwijken met verschillende bouwperioden.","Heldere intake over planning en bereikbaarheid helpt lokale uitvoering."]'::jsonb, '["Veel wijken hebben planbare toegang, maar verschillen in logistiek.","Combinatie van onderhoud en upgrades vraagt duidelijke scope."]'::jsonb, '["delft","den-haag","gouda"]'::jsonb, 'middelgrote stad', 'Groeistad met mix van naoorlogse en recente woningvoorraad.', true, true, 0.8),
  ('alphen-aan-den-rijn', 'Alphen aan den Rijn', 'Zuid-Holland', 'Groene Hart', 'C', '{"urbanDensity":"lager","buildingEraMix":"gemengd","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Alphen aan den Rijn heeft gevarieerde woonwijken.","Lokale matching profiteert van complete intakegegevens."]'::jsonb, '["Bestaande bouw en uitbreidingen vragen contextspecifieke aanpak.","Toegang en planning verschillen per wijk."]'::jsonb, '["gouda","leiden","zoetermeer"]'::jsonb, 'regionale stad', 'Stad in het Groene Hart met gemengde woningtypen.', true, true, 0.64),
  ('delft', 'Delft', 'Zuid-Holland', 'Randstad', 'C', '{"urbanDensity":"gemiddeld","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Delft heeft historische en moderne woongebieden.","Goede intake over toegang en planning helpt lokale uitvoering."]'::jsonb, '["Historische kern kan extra logistieke afstemming vragen.","Woningcontext verschilt sterk per buurt."]'::jsonb, '["den-haag","rotterdam","zoetermeer"]'::jsonb, 'regionale stad', 'Randstadstad met historische kern en gevarieerde woongebieden.', true, true, 0.64),
  ('schiedam', 'Schiedam', 'Zuid-Holland', 'Rijnmond', 'C', '{"urbanDensity":"gemiddeld","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Schiedam kent een mix van historische en naoorlogse wijken.","Lokale uitvoering vraagt heldere intake en planning."]'::jsonb, '["Historische delen vragen soms extra voorbereiding.","Toegang en werktijden verschillen per locatie."]'::jsonb, '["rotterdam","vlaardingen","delft"]'::jsonb, 'regionale stad', 'Rijnmondstad met historische en gemengde woningcontext.', true, true, 0.64),
  ('vlaardingen', 'Vlaardingen', 'Zuid-Holland', 'Rijnmond', 'C', '{"urbanDensity":"gemiddeld","buildingEraMix":"naoorlogse-mix","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Vlaardingen heeft gevarieerde woonwijken.","Lokale klussen profiteren van concrete intakegegevens."]'::jsonb, '["Woningcontext loopt uiteen per wijk.","Toegang en logistiek vooraf afstemmen helpt."]'::jsonb, '["rotterdam","schiedam","capelle-aan-den-ijssel"]'::jsonb, 'regionale stad', 'Stad met mix van naoorlogse en recente wijken.', true, true, 0.64),
  ('capelle-aan-den-ijssel', 'Capelle aan den IJssel', 'Zuid-Holland', 'Rijnmond', 'C', '{"urbanDensity":"gemiddeld","buildingEraMix":"nieuwbouw-groei","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Capelle aan den IJssel heeft gevarieerde woongebieden.","Heldere intake over planning en bereikbaarheid ondersteunt lokale uitvoering."]'::jsonb, '["Mix van appartementengebouwen en woonwijken vraagt maatwerk.","Parkeer- en toegangssituatie verschilt per buurt."]'::jsonb, '["rotterdam","vlaardingen","gouda"]'::jsonb, 'regionale stad', 'Rijnmondcontext met gevarieerde woningvoorraad.', true, true, 0.64),
  ('hoofddorp', 'Hoofddorp', 'Noord-Holland', 'Haarlemmermeer', 'C', '{"urbanDensity":"gemiddeld","buildingEraMix":"nieuwbouw-groei","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Hoofddorp heeft veel gevarieerde woonwijken.","Lokale planning profiteert van heldere intake en logistieke details."]'::jsonb, '["Woningtypen verschillen per buurt.","Toegang en materiaalrouting vooraf benoemen helpt."]'::jsonb, '["amsterdam","haarlem","zaandam"]'::jsonb, 'regionale stad', 'Haarlemmermeerstad met gemengde woningtypen.', true, true, 0.64),
  ('zaandam', 'Zaandam', 'Noord-Holland', 'Zaanstreek', 'C', '{"urbanDensity":"gemiddeld","buildingEraMix":"gemengd","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Zaandam kent uiteenlopende woonwijken.","Lokale matching werkt beter met complete intakecontext."]'::jsonb, '["Bestaande bouw en nieuwere wijken lopen door elkaar.","Toegang en planning verschillen per locatie."]'::jsonb, '["amsterdam","purmerend","alkmaar"]'::jsonb, 'regionale stad', 'Zaanstreekstad met mix van bestaande en nieuwere woonwijken.', true, true, 0.64),
  ('alkmaar', 'Alkmaar', 'Noord-Holland', 'Noord-Holland Noord', 'B', '{"urbanDensity":"gemiddeld","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Alkmaar combineert historische delen met woonwijken uit verschillende perioden.","Heldere intake over woningcontext helpt lokale uitvoering."]'::jsonb, '["Historische kern en nieuwere buurten vragen verschillende accenten.","Toegang en werkvensters verschillen per wijk."]'::jsonb, '["hoorn","purmerend","zaandam"]'::jsonb, 'middelgrote stad', 'Noord-Hollandse kern met historische en gemengde woningvoorraad.', true, true, 0.8),
  ('hilversum', 'Hilversum', 'Noord-Holland', 'Het Gooi', 'C', '{"urbanDensity":"gemiddeld","buildingEraMix":"gemengd","historicCore":false,"suburbanExpansion":false}'::jsonb, '["Hilversum heeft gevarieerde wooncontexten.","Lokale uitvoering profiteert van concrete intake over bereikbaarheid en planning."]'::jsonb, '["Woningtypen verschillen per buurt.","Praktische randvoorwaarden vooraf delen helpt."]'::jsonb, '["utrecht","amersfoort","purmerend"]'::jsonb, 'regionale stad', 'Gooi-regio stad met gevarieerde woningmix.', true, true, 0.64),
  ('purmerend', 'Purmerend', 'Noord-Holland', 'Waterland', 'C', '{"urbanDensity":"gemiddeld","buildingEraMix":"nieuwbouw-groei","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Purmerend heeft uiteenlopende woonwijken.","Goede intake ondersteunt lokale planning en uitvoering."]'::jsonb, '["Mix van bestaande bouw en uitbreiding vraagt contextspecifieke beoordeling.","Toegang en logistiek per wijk vooraf benoemen helpt."]'::jsonb, '["zaandam","hoorn","amsterdam"]'::jsonb, 'regionale stad', 'Waterlandstad met groeiende en bestaande woonwijken.', true, true, 0.64),
  ('hoorn', 'Hoorn', 'Noord-Holland', 'West-Friesland', 'C', '{"urbanDensity":"lager","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Hoorn combineert historische delen en moderne woonwijken.","Lokale intake met heldere context helpt uitvoering."]'::jsonb, '["Historische kern en nieuwere wijken vragen verschillende aanpak.","Toegang en planning verschillen per buurt."]'::jsonb, '["purmerend","alkmaar","zaandam"]'::jsonb, 'regionale stad', 'West-Friese stad met historische en gemengde woningvoorraad.', true, true, 0.64),
  ('lelystad', 'Lelystad', 'Flevoland', 'Flevoland', 'C', '{"urbanDensity":"lager","buildingEraMix":"nieuwbouw-groei","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Lelystad heeft veel jongere woonwijken.","Lokale projecten worden sterker met duidelijke intakedetails."]'::jsonb, '["Nieuwere woningvoorraad vraagt vaak planbare onderhouds- en uitbreidingsaanpak.","Toegang en logistiek per wijk vooraf bepalen helpt."]'::jsonb, '["almere","kampen","harderwijk"]'::jsonb, 'regionale stad', 'Flevolandse stad met jonge en uitbreidende woningvoorraad.', true, true, 0.64),
  ('deventer', 'Deventer', 'Overijssel', 'Stedendriehoek', 'B', '{"urbanDensity":"gemiddeld","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Deventer heeft een mix van historische delen en woonwijken.","Lokale matching profiteert van volledige intakecontext."]'::jsonb, '["Historische kern en recentere wijken vragen verschillende voorbereiding.","Bereikbaarheid en planning verschillen per buurt."]'::jsonb, '["apeldoorn","zwolle","hengelo"]'::jsonb, 'middelgrote stad', 'Stedendriehoekstad met historische en gevarieerde wooncontext.', true, true, 0.8),
  ('hengelo', 'Hengelo', 'Overijssel', 'Twente', 'C', '{"urbanDensity":"lager","buildingEraMix":"naoorlogse-mix","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Hengelo heeft gevarieerde woonwijken.","Lokale uitvoering profiteert van heldere intake en planning."]'::jsonb, '["Woningcontext verschilt per buurt.","Toegang en logistieke randvoorwaarden vooraf delen helpt."]'::jsonb, '["enschede","almelo","deventer"]'::jsonb, 'regionale stad', 'Twentse stad met gemengde woningvoorraad.', true, true, 0.64),
  ('almelo', 'Almelo', 'Overijssel', 'Twente', 'C', '{"urbanDensity":"lager","buildingEraMix":"naoorlogse-mix","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Almelo heeft verschillende woongebieden.","Heldere intake over lokale context helpt betere matching."]'::jsonb, '["Bestaande bouw en nieuwere wijken vragen verschillende aanpak.","Praktische toegangssituatie vooraf benoemen helpt."]'::jsonb, '["enschede","hengelo","deventer"]'::jsonb, 'regionale stad', 'Twentse regionale stad met gevarieerde woonwijken.', true, true, 0.64),
  ('kampen', 'Kampen', 'Overijssel', 'Regio Zwolle', 'C', '{"urbanDensity":"lager","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Kampen combineert historische kern met omliggende woonwijken.","Lokale intake met context en planning helpt uitvoering."]'::jsonb, '["Historische delen kunnen extra logistieke afstemming vragen.","Toegang en werkvensters verschillen per locatie."]'::jsonb, '["zwolle","deventer","lelystad"]'::jsonb, 'regionale stad', 'Regionale kern met historische en gemengde woningcontext.', true, true, 0.64),
  ('harderwijk', 'Harderwijk', 'Gelderland', 'Veluwe', 'C', '{"urbanDensity":"lager","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Harderwijk heeft gevarieerde woningtypen.","Lokale matching profiteert van complete intake en planning."]'::jsonb, '["Historische en nieuwere woongebieden vragen verschillende accenten.","Toegang en logistiek vooraf delen helpt."]'::jsonb, '["apeldoorn","ede","lelystad"]'::jsonb, 'regionale stad', 'Veluwe-stad met gemengde bouwperioden.', true, true, 0.64),
  ('ede', 'Ede', 'Gelderland', 'Foodvalley', 'B', '{"urbanDensity":"gemiddeld","buildingEraMix":"gemengd","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Ede heeft gevarieerde woonwijken.","Heldere intake over woningcontext en planning helpt uitvoering."]'::jsonb, '["Bestaande bouw en uitbreiding bestaan naast elkaar.","Praktische randvoorwaarden per locatie vooraf noemen helpt."]'::jsonb, '["veenendaal","wageningen","arnhem"]'::jsonb, 'middelgrote stad', 'Foodvalley stad met mix van bestaande en groeiwijken.', true, true, 0.8),
  ('veenendaal', 'Veenendaal', 'Utrecht', 'Foodvalley', 'C', '{"urbanDensity":"lager","buildingEraMix":"gemengd","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Veenendaal heeft uiteenlopende woningtypen.","Lokale intake met planning en toegang versterkt de aanvraag."]'::jsonb, '["Wijkcontext verschilt per locatie.","Toegang en logistieke details vooraf delen helpt."]'::jsonb, '["ede","wageningen","amersfoort"]'::jsonb, 'regionale stad', 'Regiostad met gevarieerde wooncontext.', true, true, 0.64),
  ('wageningen', 'Wageningen', 'Gelderland', 'Foodvalley', 'C', '{"urbanDensity":"lager","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Wageningen combineert historische en moderne wooncontext.","Duidelijke intake helpt lokale uitvoering en planning."]'::jsonb, '["Historische delen en nieuwere wijken vragen verschillende aanpak.","Praktische toegang per locatie vooraf bespreken helpt."]'::jsonb, '["ede","veenendaal","arnhem"]'::jsonb, 'regionale stad', 'Foodvalley stad met historische en gemengde woningmix.', true, true, 0.64),
  ('doetinchem', 'Doetinchem', 'Gelderland', 'Achterhoek', 'C', '{"urbanDensity":"lager","buildingEraMix":"naoorlogse-mix","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Doetinchem heeft gevarieerde woonwijken.","Lokale matching profiteert van volledige intakecontext."]'::jsonb, '["Bestaande bouw en uitbreiding komen naast elkaar voor.","Toegang en planning verschillen per buurt."]'::jsonb, '["arnhem","zutphen","deventer"]'::jsonb, 'regionale stad', 'Achterhoekse stad met gemengde woonwijken.', true, true, 0.64),
  ('zutphen', 'Zutphen', 'Gelderland', 'Achterhoek', 'C', '{"urbanDensity":"lager","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Zutphen combineert historische delen en woonwijken.","Lokale intake met context en planning helpt uitvoering."]'::jsonb, '["Historische woningcontext vraagt soms extra voorbereiding.","Toegang en werktijden verschillen per locatie."]'::jsonb, '["deventer","doetinchem","apeldoorn"]'::jsonb, 'regionale stad', 'Historische Achterhoekstad met gevarieerde woningmix.', true, true, 0.64),
  ('assen', 'Assen', 'Drenthe', 'Noord-Drenthe', 'C', '{"urbanDensity":"lager","buildingEraMix":"naoorlogse-mix","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Assen heeft gevarieerde woonwijken.","Lokale planning wordt sterker met complete intakeinformatie."]'::jsonb, '["Woningcontext verschilt per wijk.","Toegang en logistieke randvoorwaarden vooraf delen helpt."]'::jsonb, '["groningen","emmen","heerenveen"]'::jsonb, 'regionale stad', 'Drentse hoofdstad met gemengde wooncontext.', true, true, 0.64),
  ('emmen', 'Emmen', 'Drenthe', 'Zuidoost-Drenthe', 'C', '{"urbanDensity":"lager","buildingEraMix":"naoorlogse-mix","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Emmen heeft verschillende woongebieden.","Heldere intake over planning en situatie helpt lokale uitvoering."]'::jsonb, '["Bestaande bouw en groeiwijken vragen verschillende aanpak.","Toegang en logistiek per locatie vooraf benoemen helpt."]'::jsonb, '["assen","groningen","heerenveen"]'::jsonb, 'regionale stad', 'Regionale stad met gevarieerde woningvoorraad.', true, true, 0.64),
  ('drachten', 'Drachten', 'Friesland', 'Zuidoost-Friesland', 'C', '{"urbanDensity":"lager","buildingEraMix":"nieuwbouw-groei","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Drachten heeft gevarieerde woonwijken.","Lokale matching profiteert van complete intake en planning."]'::jsonb, '["Veel woonwijken vragen planbare uitvoering.","Toegang en logistieke details vooraf delen helpt."]'::jsonb, '["heerenveen","leeuwarden","sneek"]'::jsonb, 'regionale stad', 'Friese stad met gemengde en groeiende woningcontext.', true, true, 0.64),
  ('sneek', 'Sneek', 'Friesland', 'Zuidwest-Friesland', 'C', '{"urbanDensity":"lager","buildingEraMix":"historische-kern-mix","historicCore":true,"suburbanExpansion":false}'::jsonb, '["Sneek combineert historische kern met omliggende woonwijken.","Lokale intake met context en planning helpt uitvoering."]'::jsonb, '["Historische delen vragen soms extra voorbereiding.","Toegang en planning verschillen per wijk."]'::jsonb, '["leeuwarden","heerenveen","drachten"]'::jsonb, 'regionale stad', 'Historische Friese kernstad met gevarieerde woningmix.', true, true, 0.64),
  ('heerenveen', 'Heerenveen', 'Friesland', 'Zuidoost-Friesland', 'C', '{"urbanDensity":"lager","buildingEraMix":"gemengd","historicCore":false,"suburbanExpansion":true}'::jsonb, '["Heerenveen heeft uiteenlopende woningtypen.","Heldere intake over planning en bereikbaarheid ondersteunt lokale uitvoering."]'::jsonb, '["Bestaande bouw en uitbreiding vragen contextspecifieke aanpak.","Toegang en logistiek vooraf afstemmen helpt."]'::jsonb, '["leeuwarden","drachten","sneek"]'::jsonb, 'regionale stad', 'Friese regionale stad met gemengde woningvoorraad.', true, true, 0.64)
on conflict (slug) do update set
  name = excluded.name,
  province = excluded.province,
  region_label = excluded.region_label,
  tier = excluded.tier,
  content_profile = excluded.content_profile,
  intro_facts = excluded.intro_facts,
  local_characteristics = excluded.local_characteristics,
  nearby_city_slugs = excluded.nearby_city_slugs,
  population_band = excluded.population_band,
  housing_notes = excluded.housing_notes,
  published = excluded.published,
  indexable = excluded.indexable,
  priority = excluded.priority,
  updated_at = timezone('utc', now());

update public.seo_locations
set tier = case
  when slug in ('amsterdam','rotterdam','den-haag','utrecht','eindhoven','groningen','tilburg','breda','nijmegen','arnhem','haarlem','almere','zwolle','amersfoort') then 'A'
  when slug in ('maastricht','enschede','leiden','den-bosch','apeldoorn','deventer','alkmaar','ede','gouda','zoetermeer') then 'B'
  else coalesce(tier, 'C')
end;

update public.seo_local_pages
set
  quality_score = greatest(quality_score, 0),
  duplicate_risk = case when duplicate_risk in ('low', 'medium', 'high') then duplicate_risk else 'high' end,
  coverage_status = case when coverage_status in ('none', 'limited', 'sufficient') then coverage_status else 'none' end;
